video_src="https://www.youtube.com/embed/1rjH98cvqsg";

pre_sections = [
  [2,8,"Intro"],
  [8,8,"Verse 1"],
  [4,8,"Pre-Chorus 1"],
  [8,8,"Chorus 1"],
  [2,8,"Interlude"],
  [8,8,"Verse 2"],
  [4,8,"Pre-Chorus 2"],
  [8,8,"Chorus 2"],
  [4,8,"Repeat Chorus"],
  [7,8,"Ending"],
];

pre_comments = [
  [81,112,"Follow this video"],
  [113,144,"New order for the 2nd grays"],
  [145,168,"Pivot rotate"],
  [281,284,"Get ready to stand on 5"],
  [285,288,"STAND"],
  [289,352,"Exact positions will vary"],
];

models = [
  {
    name:"Derrick",
    start: "middle",
    pre_moves: [
      [4,"delay"],
      [12,"up"],
      [64,"pose"],
      [32,"pose"],
      [7,"down"],
      [1,"pose"],
      [24,"pose"],
      [5,"down"],
    ],
    moves: [],
    color:"green",
  },




  {
    name:"Melody W",
    start: "middle left",
    pre_moves: [
      [4,"delay"],
      [4,"left"],
      [16,"pose"],
      [2,1,0],
      [6,"pose"],
      [8,"pose"],
      [2,1,0],
      [6,"pose"],
      [8,"pose"],
      [2,1,0],
      [6,"pose"],
      [4,"diag nw"],
      [4,"pose"],
      [4,"right"],
      [4,"up"],
      [8,"up half speed"],
      [8,"pose"],
      [16,"down half speed"],
      [4,"left"],
      [4,"down"],
      [4,"right"],
    ],
    moves: [],
    color:"red",
  },
  {
    name:"Shyam",
    start: "middle right",
    pre_moves: [
      [4,"delay"],
      [4,"right"],
      [16,"pose"],
      [2,-1,0],
      [6,"pose"],
      [8,"pose"],
      [2,-1,0],
      [6,"pose"],
      [8,"pose"],
      [2,-1,0],
      [6,"pose"],
      [4,"diag ne"],
      [4,"pose"],
      [4,"left"],
      [4,"up"],
      [8,"up half speed"],
      [8,"pose"],
      [16,"down half speed"],
      [8,"left"],
      [4,"down"],
      [4,"right"],
    ],
    moves: [],
    color:"red",
  },

  {
    name:"Chris Y",
    start: "middle left",
    pre_moves: [
      [5,"delay"],
      [3,"left"],
      [16,"pose"],
      [2,1,0],
      [6,"pose"],
      [8,"pose"],
      [2,1,0],
      [6,"pose"],
      [4,"diag nw"],
      [4,"pose"],
      [4,"right"],
      [8,"up"],
      [4,"pose"],
      [1,2,1],
      [7,"down"],
      [8,-6,0,"half speed"],
      [8,"right half speed"],
      [8,"down half speed"],
      [8,"left half speed"],
      [4,"right"],
    ],
    moves: [],
    color:"green",
  },
  {
    name:"Michele T",
    start: "middle right",
    pre_moves: [
      [5,"delay"],
      [3,"right"],
      [16,"pose"],
      [2,-1,0],
      [6,"pose"],
      [8,"pose"],
      [2,-1,0],
      [6,"pose"],
      [4,"diag ne"],
      [4,"pose"],
      [4,"left"],
      [8,"up"],
      [4,"pose"],
      [1,-2,1],
      [7,"down"],
      [8,6,0,"half speed"],
      [8,"left half speed"],
      [8,"down half speed"],
      [8,"right half speed"],
      [4,"up"],
      [12,"left"],
      [4,"down"],
      [4,"right"],
    ],
    moves: [],
    color:"green",
  },

  {
    name:"Alvin",
    start: "middle left",
    pre_moves: [
      [6,"delay"],
      [2,"left"],
      [16,"pose"],
      [2,1,0],
      [6,"pose"],
      [4,"diag nw"],
      [4,"pose"],
      [4,"right"],
      [8,"up"],
      [4,"pose"],
      [1,2,1],
      [7,"down"],
      [4,-4,4],
      [4,"pose"],
      [2,1,0],
      [6,"pose"],
      [8,-3,0,"half speed"],
      [8,"up half speed"],
      [8,"right half speed"],
      [8,"down half speed"],
    ],
    moves: [],
    color:"blue",
  },
  {
    name:"Jeff",
    start: "middle right",
    pre_moves: [
      [6,"delay"],
      [2,"right"],
      [16,"pose"],
      [2,-1,0],
      [6,"pose"],
      [4,"diag ne"],
      [4,"pose"],
      [4,"left"],
      [8,"up"],
      [4,"pose"],
      [1,-2,1],
      [7,"down"],
      [4,4,4],
      [4,"pose"],
      [2,-1,0],
      [6,"pose"],
      [8,3,0,"half speed"],
      [8,"up half speed"],
      [8,"left half speed"],
      [8,"down half speed"],
      [4,"right"],
      [4,"up"],
      [12,"left"],
      [4,"down"],
      [4,"right"],
    ],
    moves: [],
    color:"blue",
  },

  {
    name:"Dom",
    start: "middle left",
    pre_moves: [
      [7,"delay"],
      [1,"left"],
      [8,"pose"],
      [4,"diag nw"],
      [4,"pose"],
      [4,"right"],
      [8,"up"],
      [4,"pose"],
      [1,2,1],
      [7,"down"],
      [4,-4,4],
      [4,"pose"],
      [2,1,0],
      [6,"pose"],
      [8,"pose"],
      [2,1,0],
      [6,"pose"],
      [8,"up half speed"],
      [8,"down half speed"],
      [8,"left half speed"],
      [8,"up half speed"],
      [4,"down"],
      [4,"right"],
    ],
    moves: [],
    color:"orange",
  },
  {
    name:"Cynthia",
    start: "middle right",
    pre_moves: [
      [7,"delay"],
      [1,"right"],
      [8,"pose"],
      [4,"diag ne"],
      [4,"pose"],
      [4,"left"],
      [8,"up"],
      [4,"pose"],
      [1,-2,1],
      [7,"down"],
      [4,4,4],
      [4,"pose"],
      [2,-1,0],
      [6,"pose"],
      [8,"pose"],
      [2,-1,0],
      [6,"pose"],
      [8,"up half speed"],
      [8,"down half speed"],
      [8,"right half speed"],
      [8,"up half speed"],
      [12,"left"],
      [4,"down"],
      [4,"right"],
    ],
    moves: [],
    color:"orange",
  },



  {
    name:"Josh",
    start: "left",
    pre_moves: [
      [112,"delay"],
      [8,"right"],
      [4,"up"],
      [12,"left"],
      [4,"down"],
      [4,"right"],
      [4,-3,-2,"pivot"],
      [4,"pose"],
      [4,3,-2,"pivot"],
      [4,"pose"],
      [8,"up"],
      [4,"pose"],
      [1,2,1],
      [11,"down"],
    ],
    moves: [],
    color:"gray",
  },
  {
    name:"Melody T",
    start: "left",
    pre_moves: [
      [112,"delay"],
      [4,"delay"],
      [8,"right"],
      [4,"up"],
      [12,"left"],
      [4,"down"],
      [4,"diag ne pivot"],
      [4,"pose"],
      [8,"up"],
      [4,"pose"],
      [1,2,1],
      [11,"down"],
    ],
    moves: [],
    color:"gray",
  },
  {
    name:"Brandon",
    start: "left",
    pre_moves: [
      [112,"delay"],
      [8,"delay"],
      [8,"right"],
      [4,"up"],
      [12,"left"],
      [4,"diag se pivot"],
      [4,"pose"],
      [4,-3,-2,"pivot"],
      [4,"pose"],
      [4,3,-2,"pivot"],
      [4,"pose"],
      [8,"up"],
      [4,"pose"],
      [1,2,1],
      [11,"down"],
    ],
    moves: [],
    color:"gray",
  },
  {
    name:"Christina",
    start: "left",
    pre_moves: [
      [112,"delay"],
      [12,"delay"],
      [8,"right"],
      [4,"up"],
      [8,"left"],
      [8,"up"],
      [4,"pose"],
      [1,2,1],
      [11,"down"],
    ],
    moves: [],
    color:"gray",
  },
  {
    name:"Jeremy G",
    start: "left",
    pre_moves: [
      [112,"delay"],
      [16,"delay"],
      [8,"right"],
      [4,"up"],
      [4,"left"],
      [8,"up"],
      [4,"pose"],
      [1,-2,1],
      [11,"down"],
    ],
    moves: [],
    color:"gray",
  },
  {
    name:"Maggie",
    start: "left",
    pre_moves: [
      [112,"delay"],
      [20,"delay"],
      [8,"right"],
      [4,"up"],
      [4,"diag sw pivot"],
      [4,"pose"],
      [4,3,-2,"pivot"],
      [4,"pose"],
      [4,-3,-2,"pivot"],
      [4,"pose"],
      [8,"up"],
      [4,"pose"],
      [1,-2,1],
      [11,"down"],
    ],
    moves: [],
    color:"gray",
  },
  {
    name:"Eric",
    start: "left",
    pre_moves: [
      [112,"delay"],
      [24,"delay"],
      [8,"right"],
      [4,"diag nw pivot"],
      [4,"pose"],
      [8,"up"],
      [4,"pose"],
      [1,-2,1],
      [11,"down"],
    ],
    moves: [],
    color:"gray",
  },
  {
    name:"Julianne",
    start: "left",
    pre_moves: [
      [112,"delay"],
      [28,"delay"],
      [4,"right"],
      [4,3,-2,"pivot"],
      [4,"pose"],
      [4,-3,-2,"pivot"],
      [4,"pose"],
      [8,"up"],
      [4,"pose"],
      [1,-2,1],
      [11,"down"],
    ],
    moves: [],
    color:"gray",
  },











  {
    name:"Iris",
    start: "left",
    pre_moves: [
      [192,"delay"],
      [8,"up"],
      [4,"diag ne"],
      [4,"pose"],
      [1,-2,1],
      [7,"down"],
      [4,-6,0],
      [36,"pose"],
      [28,"kneel"],
      [4,"pose"],
      [4,"right"],
      [8,"up"],
      [1,1,1],
      [3,"down"],
      [16,"pose"],
      [8,"down"],
      [4,-5,0],
      [4,"up"],
      [16,"pose"],
      [4,"right"],
      [8,"up"],
      [1,1,1],
      [11,"down"],
      [4,-5,0],
      [4,"up"],
      [4,"right"],
      [8,"up"],
      [1,2,1],
      [11,"down"],
    ],
    moves: [],
    color:"red",
  },
  {
    name:"Jen",
    start: "right",
    pre_moves: [
      [192,"delay"],
      [8,"up"],
      [4,"diag nw"],
      [4,"pose"],
      [1,2,1],
      [7,"down"],
      [4,6,0],
      [36,"pose"],
      [28,"kneel"],
      [4,"pose"],
      [16,"pose"],
      [4,"left"],
      [8,"up"],
      [1,-1,1],
      [3,"down"],
      [16,"pose"],
      [8,"down"],
      [4,5,0],
      [4,"up"],
      [4,"left"],
      [8,"up"],
      [1,-1,1],
      [11,"down"],
      [4,5,0],
      [4,"up"],
      [4,"left"],
      [8,"up"],
      [1,-2,1],
      [11,"down"],
    ],
    moves: [],
    color:"blue",
  },

  {
    name:"Peter",
    start: "left",
    pre_moves: [
      [192,"delay"],
      [16,"delay"],
      [8,"up"],
      [4,"diag ne"],
      [4,"pose"],
      [1,-2,1],
      [7,"down"],
      [2,"right"],
      [22,"pose"],
      [28,"kneel"],
      [4,"pose"],
      [16,"pose"],
      [8,"up"],
      [1,-1,1],
      [7,"down"],
      [16,"pose"],
      [4,"down"],
      [4,5,0],
      [4,"up"],
      [4,"left"],
      [8,"up"],
      [1,-1,1],
      [11,"down"],
      [4,5,0],
      [4,"up"],
      [4,"left"],
      [8,"up"],
      [1,-2,1],
      [11,"down"],
    ],
    moves: [],
    color:"blue",
  },
  {
    name:"Shawn",
    start: "right",
    pre_moves: [
      [192,"delay"],
      [16,"delay"],
      [8,"up"],
      [4,"diag nw"],
      [4,"pose"],
      [1,2,1],
      [7,"down"],
      [2,"left"],
      [22,"pose"],
      [28,"kneel"],
      [4,"pose"],
      [8,"up"],
      [1,1,1],
      [7,"down"],
      [16,"pose"],
      [4,"down"],
      [4,-5,0],
      [4,"up"],
      [4,"right"],
      [16,"pose"],
      [8,"up"],
      [1,1,1],
      [11,"down"],
      [4,-5,0],
      [4,"up"],
      [4,"right"],
      [8,"up"],
      [1,2,1],
      [11,"down"],
    ],
    moves: [],
    color:"red",
  },

  {
    name:"Allysa",
    start: "left",
    pre_moves: [
      [192,"delay"],
      [32,"delay"],
      [8,"up"],
      [4,"diag ne"],
      [4,"pose"],
      [1,-2,1],
      [3,"down"],
      [2,"left"],
      [10,"pose"],
      [28,"kneel"],
      [4,"pose"],
      [4,"up"],
      [1,1,1],
      [11,"down"],
      [16,"pose"],
      [4,-5,0],
      [4,"up"],
      [4,"right"],
      [4,"up"],
      [16,"pose"],
      [4,"up"],
      [1,1,1],
      [11,"down"],
      [4,-5,0],
      [4,"up"],
      [4,"right"],
      [8,"up"],
      [1,2,1],
      [11,"down"],
    ],
    moves: [],
    color:"red",
  },
  {
    name:"Isabelle",
    start: "right",
    pre_moves: [
      [192,"delay"],
      [32,"delay"],
      [8,"up"],
      [4,"diag nw"],
      [4,"pose"],
      [1,2,1],
      [3,"down"],
      [2,"right"],
      [10,"pose"],
      [28,"kneel"],
      [4,"pose"],
      [16,"pose"],
      [4,"up"],
      [1,-1,1],
      [11,"down"],
      [16,"pose"],
      [4,5,0],
      [4,"up"],
      [4,"left"],
      [4,"up"],
      [4,"up"],
      [1,-1,1],
      [11,"down"],
      [4,5,0],
      [4,"up"],
      [4,"left"],
      [8,"up"],
      [1,-2,1],
      [11,"down"],
    ],
    moves: [],
    color:"blue",
  },

  {
    name:"Nick L",
    start: "middle left",
    pre_moves: [
      [192,"delay"],
      [48,"delay"],
      [8,"up"],
      [4,3,-4],
      [4,"pose"],
      [28,"kneel"],
      [4,"pose"],
      [16,"pose"],
      [1,-1,1],
      [11,"down"],
      [4,5,0],
      [16,"pose"],
      [4,"up"],
      [4,"left"],
      [8,"up"],
      [1,-1,1],
      [11,"down"],
      [4,5,0],
      [4,"up"],
      [4,"left"],
      [8,"up"],
      [1,-2,1],
      [11,"down"],
    ],
    moves: [],
    color:"blue",
  },
  {
    name:"John",
    start: "middle right",
    pre_moves: [
      [192,"delay"],
      [48,"delay"],
      [8,"up"],
      [4,-3,-4],
      [4,"pose"],
      [28,"kneel"],
      [4,"pose"],
      [1,1,1],
      [11,"down"],
      [4,-5,0],
      [16,"pose"],
      [4,"up"],
      [4,"right"],
      [8,"up"],
      [16,"pose"],
      [1,1,1],
      [11,"down"],
      [4,-5,0],
      [4,"up"],
      [4,"right"],
      [8,"up"],
      [1,2,1],
      [11,"down"],
    ],
    moves: [],
    color:"red",
  },




  {
    name:"Sam",
    start: "middle left",
    pre_moves: [
      [256,"delay"],
      [10,"up"],
      [2,"pose"],
      [20,"pose"],
      [10,"down"],
      [3,-5,0],
      [3,0,-4],
      [16,"pose"],
      [4,"right"],
      [8,"up"],
      [1,1,1],
      [3,"down"],
      [16,"pose"],
      [8,"down"],
      [4,-5,0],
      [4,"up"],
      [4,"right"],
      [8,"up"],
      [1,2,1],
      [11,"down"],
    ],
    moves: [],
    color:"red",
  },
  {
    name:"Kevin",
    start: "middle right",
    pre_moves: [
      [256,"delay"],
      [10,"up"],
      [2,"pose"],
      [20,"pose"],
      [16,"pose"],
      [10,"down"],
      [3,5,0],
      [3,0,-4],
      [16,"pose"],
      [4,"left"],
      [8,"up"],
      [1,-1,1],
      [3,"down"],
      [8,"down"],
      [4,5,0],
      [4,"up"],
      [4,"left"],
      [8,"up"],
      [1,-2,1],
      [11,"down"],
    ],
    moves: [],
    color:"blue",
  },

  {
    name:"Sabrina",
    start: "middle left",
    pre_moves: [
      [256,"delay"],
      [8,"delay"],
      [6,"up"],
      [2,"pose"],
      [16,"pose"],
      [6,"down"],
      [4,-5,0],
      [3,0,-4],
      [3,4,0],
      [16,"pose"],
      [8,"up"],
      [1,1,1],
      [7,"down"],
      [16,"pose"],
      [4,"down"],
      [4,-5,0],
      [4,"up"],
      [4,"right"],
      [8,"up"],
      [1,2,1],
      [11,"down"],
    ],
    moves: [],
    color:"red",
  },
  {
    name:"Eurie",
    start: "middle right",
    pre_moves: [
      [256,"delay"],
      [8,"delay"],
      [6,"up"],
      [2,"pose"],
      [16,"pose"],
      [16,"pose"],
      [6,"down"],
      [4,5,0],
      [3,0,-4],
      [3,-4,0],
      [16,"pose"],
      [8,"up"],
      [1,-1,1],
      [7,"down"],
      [4,"down"],
      [4,5,0],
      [4,"up"],
      [4,"left"],
      [8,"up"],
      [1,-2,1],
      [11,"down"],
    ],
    moves: [],
    color:"blue",
  },

  {
    name:"Elaine",
    start: "middle left",
    pre_moves: [
      [256,"delay"],
      [16,"delay"],
      [4,-5,0],
      [12,"pose"],
      [4,"up"],
      [4,"right"],
      [8,"up"],
      [16,"pose"],
      [1,1,1],
      [11,"down"],
      [4,-5,0],
      [16,"pose"],
      [4,"up"],
      [4,"right"],
      [8,"up"],
      [1,1,1],
      [11,"down"],
      [4,-5,0],
      [4,"up"],
      [4,"right"],
      [8,"up"],
      [1,2,1],
      [11,"down"],
    ],
    moves: [],
    color:"red",
  },
  {
    name:"Chris M",
    start: "middle right",
    pre_moves: [
      [256,"delay"],
      [16,"delay"],
      [4,5,0],
      [12,"pose"],
      [16,"pose"],
      [4,"up"],
      [4,"left"],
      [8,"up"],
      [16,"pose"],
      [1,-1,1],
      [11,"down"],
      [4,5,0],
      [4,"up"],
      [4,"left"],
      [8,"up"],
      [1,-1,1],
      [11,"down"],
      [4,5,0],
      [4,"up"],
      [4,"left"],
      [8,"up"],
      [1,-2,1],
      [11,"down"],
    ],
    moves: [],
    color:"blue",
  },

  {
    name:"June (J)",
    start: "middle left",
    pre_moves: [
      [256,"delay"],
      [24,"delay"],
      [8,"pose"],
      [4,-5,0],
      [4,"up"],
      [4,"right"],
      [4,"up"],
      [16,"pose"],
      [4,"up"],
      [1,1,1],
      [11,"down"],
      [16,"pose"],
      [4,-5,0],
      [4,"up"],
      [4,"right"],
      [8,"up"],
      [1,2,1],
      [11,"down"],
    ],
    moves: [],
    color:"red",
  },
  {
    name:"Michelle F",
    start: "middle right",
    pre_moves: [
      [256,"delay"],
      [24,"delay"],
      [8,"pose"],
      [16,"pose"],
      [4,5,0],
      [4,"up"],
      [4,"left"],
      [4,"up"],
      [16,"pose"],
      [4,"up"],
      [1,-1,1],
      [11,"down"],
      [4,5,0],
      [4,"up"],
      [4,"left"],
      [8,"up"],
      [1,-2,1],
      [11,"down"],
    ],
    moves: [],
    color:"blue",
  },






  {
    name:"Derrick",
    start: "right",
    pre_moves: [
      [384,"delay"],
      [4,"right"],
      [4,"up"],
      [4,"left"],
      [8,"up"],
      [48,"pose"],
    ],
    moves: [],
    color:"green",
  },
  {
    name:"Tim",
    start: "left",
    pre_moves: [
      [384,"delay"],
      [4,"left"],
      [4,"up"],
      [4,"right"],
      [8,"up"],
      [48,"pose"],
    ],
    moves: [],
    color:"red",
  },
]
