video_src="https://www.youtube.com/embed/1rjH98cvqsg";

pre_sections = [
  {"measures":2, "counts":8, "text":"Intro"},
  {"measures":8, "counts":8, "text":"Verse 1"},
  {"measures":4, "counts":8, "text":"Pre-Chorus 1"},
  {"measures":8, "counts":8, "text":"Chorus 1"},
  {"measures":2, "counts":8, "text":"Interlude"},
  {"measures":8, "counts":8, "text":"Verse 2"},
  {"measures":4, "counts":8, "text":"Pre-Chorus 2"},
  {"measures":8, "counts":8, "text":"Chorus 2"},
  {"measures":4, "counts":8, "text":"Repeat Chorus"},
  {"measures":7, "counts":8, "text":"Ending"}
];

pre_comments = [
  {"startCount":81, "endCount":112, "text":"Follow this video"},
  {"startCount":113, "endCount":144, "text":"New order for the 2nd grays"},
  {"startCount":145, "endCount":168, "text":"Pivot rotate"},
  {"startCount":281, "endCount":284, "text":"Get ready to stand on 5"},
  {"startCount":285, "endCount":288, "text":"STAND"},
  {"startCount":289, "endCount":352, "text":"Exact positions will vary"}
];

models = [
  {
    "name":"Derrick",
    "start":"middle",
    "pre_moves":[
      {"count":4, "type":"delay"},
      {"count":12, "type":"up"},
      {"count":64, "type":"pose"},
      {"count":32, "type":"pose"},
      {"count":7, "type":"down"},
      {"count":1, "type":"pose"},
      {"count":24, "type":"pose"},
      {"count":5, "type":"down"}
    ],
    "color":"green"
  },
  {
    "name":"Melody W",
    "start":"middle left",
    "pre_moves":[
      {"count":4, "type":"delay"},
      {"count":4, "type":"left"},
      {"count":16, "type":"pose"},
      {"count":2, "dx":1, "dy":0, "type":""},
      {"count":6, "type":"pose"},
      {"count":8, "type":"pose"},
      {"count":2, "dx":1, "dy":0, "type":""},
      {"count":6, "type":"pose"},
      {"count":8, "type":"pose"},
      {"count":2, "dx":1, "dy":0, "type":""},
      {"count":6, "type":"pose"},
      {"count":4, "type":"diag nw"},
      {"count":4, "type":"pose"},
      {"count":4, "type":"right"},
      {"count":4, "type":"up"},
      {"count":8, "type":"up half speed"},
      {"count":8, "type":"pose"},
      {"count":16, "type":"down half speed"},
      {"count":4, "type":"left"},
      {"count":4, "type":"down"},
      {"count":4, "type":"right"}
    ],
    "color":"red"
  },
  {
    "name":"Shyam",
    "start":"middle right",
    "pre_moves":[
      {"count":4, "type":"delay"},
      {"count":4, "type":"right"},
      {"count":16, "type":"pose"},
      {"count":2, "dx":-1, "dy":0, "type":""},
      {"count":6, "type":"pose"},
      {"count":8, "type":"pose"},
      {"count":2, "dx":-1, "dy":0, "type":""},
      {"count":6, "type":"pose"},
      {"count":8, "type":"pose"},
      {"count":2, "dx":-1, "dy":0, "type":""},
      {"count":6, "type":"pose"},
      {"count":4, "type":"diag ne"},
      {"count":4, "type":"pose"},
      {"count":4, "type":"left"},
      {"count":4, "type":"up"},
      {"count":8, "type":"up half speed"},
      {"count":8, "type":"pose"},
      {"count":16, "type":"down half speed"},
      {"count":8, "type":"left"},
      {"count":4, "type":"down"},
      {"count":4, "type":"right"}
    ],
    "color":"red"
  },
  {
    "name":"Chris Y",
    "start":"middle left",
    "pre_moves":[
      {"count":5, "type":"delay"},
      {"count":3, "type":"left"},
      {"count":16, "type":"pose"},
      {"count":2, "dx":1, "dy":0, "type":""},
      {"count":6, "type":"pose"},
      {"count":8, "type":"pose"},
      {"count":2, "dx":1, "dy":0, "type":""},
      {"count":6, "type":"pose"},
      {"count":4, "type":"diag nw"},
      {"count":4, "type":"pose"},
      {"count":4, "type":"right"},
      {"count":8, "type":"up"},
      {"count":4, "type":"pose"},
      {"count":1, "dx":2, "dy":1, "type":""},
      {"count":7, "type":"down"},
      {"count":8, "dx":-6, "dy":0, "type":"half speed"},
      {"count":8, "type":"right half speed"},
      {"count":8, "type":"down half speed"},
      {"count":8, "type":"left half speed"},
      {"count":4, "type":"right"}
    ],
    "color":"green"
  },
  {
    "name":"Michele T",
    "start":"middle right",
    "pre_moves":[
      {"count":5, "type":"delay"},
      {"count":3, "type":"right"},
      {"count":16, "type":"pose"},
      {"count":2, "dx":-1, "dy":0, "type":""},
      {"count":6, "type":"pose"},
      {"count":8, "type":"pose"},
      {"count":2, "dx":-1, "dy":0, "type":""},
      {"count":6, "type":"pose"},
      {"count":4, "type":"diag ne"},
      {"count":4, "type":"pose"},
      {"count":4, "type":"left"},
      {"count":8, "type":"up"},
      {"count":4, "type":"pose"},
      {"count":1, "dx":-2, "dy":1, "type":""},
      {"count":7, "type":"down"},
      {"count":8, "dx":6, "dy":0, "type":"half speed"},
      {"count":8, "type":"left half speed"},
      {"count":8, "type":"down half speed"},
      {"count":8, "type":"right half speed"},
      {"count":4, "type":"up"},
      {"count":12, "type":"left"},
      {"count":4, "type":"down"},
      {"count":4, "type":"right"}
    ],
    "color":"green"
  },
  {
    "name":"Alvin",
    "start":"middle left",
    "pre_moves":[
      {"count":6, "type":"delay"},
      {"count":2, "type":"left"},
      {"count":16, "type":"pose"},
      {"count":2, "dx":1, "dy":0, "type":""},
      {"count":6, "type":"pose"},
      {"count":4, "type":"diag nw"},
      {"count":4, "type":"pose"},
      {"count":4, "type":"right"},
      {"count":8, "type":"up"},
      {"count":4, "type":"pose"},
      {"count":1, "dx":2, "dy":1, "type":""},
      {"count":7, "type":"down"},
      {"count":4, "dx":-4, "dy":4, "type":""},
      {"count":4, "type":"pose"},
      {"count":2, "dx":1, "dy":0, "type":""},
      {"count":6, "type":"pose"},
      {"count":8, "dx":-3, "dy":0, "type":"half speed"},
      {"count":8, "type":"up half speed"},
      {"count":8, "type":"right half speed"},
      {"count":8, "type":"down half speed"}
    ],
    "color":"blue"
  },
  {
    "name":"Jeff",
    "start":"middle right",
    "pre_moves":[
      {"count":6, "type":"delay"},
      {"count":2, "type":"right"},
      {"count":16, "type":"pose"},
      {"count":2, "dx":-1, "dy":0, "type":""},
      {"count":6, "type":"pose"},
      {"count":4, "type":"diag ne"},
      {"count":4, "type":"pose"},
      {"count":4, "type":"left"},
      {"count":8, "type":"up"},
      {"count":4, "type":"pose"},
      {"count":1, "dx":-2, "dy":1, "type":""},
      {"count":7, "type":"down"},
      {"count":4, "dx":4, "dy":4, "type":""},
      {"count":4, "type":"pose"},
      {"count":2, "dx":-1, "dy":0, "type":""},
      {"count":6, "type":"pose"},
      {"count":8, "dx":3, "dy":0, "type":"half speed"},
      {"count":8, "type":"up half speed"},
      {"count":8, "type":"left half speed"},
      {"count":8, "type":"down half speed"},
      {"count":4, "type":"right"},
      {"count":4, "type":"up"},
      {"count":12, "type":"left"},
      {"count":4, "type":"down"},
      {"count":4, "type":"right"}
    ],
    "color":"blue"
  },
  {
    "name":"Dom",
    "start":"middle left",
    "pre_moves":[
      {"count":7, "type":"delay"},
      {"count":1, "type":"left"},
      {"count":8, "type":"pose"},
      {"count":4, "type":"diag nw"},
      {"count":4, "type":"pose"},
      {"count":4, "type":"right"},
      {"count":8, "type":"up"},
      {"count":4, "type":"pose"},
      {"count":1, "dx":2, "dy":1, "type":""},
      {"count":7, "type":"down"},
      {"count":4, "dx":-4, "dy":4, "type":""},
      {"count":4, "type":"pose"},
      {"count":2, "dx":1, "dy":0, "type":""},
      {"count":6, "type":"pose"},
      {"count":8, "type":"pose"},
      {"count":2, "dx":1, "dy":0, "type":""},
      {"count":6, "type":"pose"},
      {"count":8, "type":"up half speed"},
      {"count":8, "type":"down half speed"},
      {"count":8, "type":"left half speed"},
      {"count":8, "type":"up half speed"},
      {"count":4, "type":"down"},
      {"count":4, "type":"right"}
    ],
    "color":"orange"
  },
  {
    "name":"Cynthia",
    "start":"middle right",
    "pre_moves":[
      {"count":7, "type":"delay"},
      {"count":1, "type":"right"},
      {"count":8, "type":"pose"},
      {"count":4, "type":"diag ne"},
      {"count":4, "type":"pose"},
      {"count":4, "type":"left"},
      {"count":8, "type":"up"},
      {"count":4, "type":"pose"},
      {"count":1, "dx":-2, "dy":1, "type":""},
      {"count":7, "type":"down"},
      {"count":4, "dx":4, "dy":4, "type":""},
      {"count":4, "type":"pose"},
      {"count":2, "dx":-1, "dy":0, "type":""},
      {"count":6, "type":"pose"},
      {"count":8, "type":"pose"},
      {"count":2, "dx":-1, "dy":0, "type":""},
      {"count":6, "type":"pose"},
      {"count":8, "type":"up half speed"},
      {"count":8, "type":"down half speed"},
      {"count":8, "type":"right half speed"},
      {"count":8, "type":"up half speed"},
      {"count":12, "type":"left"},
      {"count":4, "type":"down"},
      {"count":4, "type":"right"}
    ],
    "color":"orange"
  },
  {
    "name":"Josh",
    "start":"left",
    "pre_moves":[
      {"count":112, "type":"delay"},
      {"count":8, "type":"right"},
      {"count":4, "type":"up"},
      {"count":12, "type":"left"},
      {"count":4, "type":"down"},
      {"count":4, "type":"right"},
      {"count":4, "dx":-3, "dy":-2, "type":"pivot"},
      {"count":4, "type":"pose"},
      {"count":4, "dx":3, "dy":-2, "type":"pivot"},
      {"count":4, "type":"pose"},
      {"count":8, "type":"up"},
      {"count":4, "type":"pose"},
      {"count":1, "dx":2, "dy":1, "type":""},
      {"count":11, "type":"down"}
    ],
    "color":"gray"
  },
  {
    "name":"Melody T",
    "start":"left",
    "pre_moves":[
      {"count":112, "type":"delay"},
      {"count":4, "type":"delay"},
      {"count":8, "type":"right"},
      {"count":4, "type":"up"},
      {"count":12, "type":"left"},
      {"count":4, "type":"down"},
      {"count":4, "type":"diag ne pivot"},
      {"count":4, "type":"pose"},
      {"count":8, "type":"up"},
      {"count":4, "type":"pose"},
      {"count":1, "dx":2, "dy":1, "type":""},
      {"count":11, "type":"down"}
    ],
    "color":"gray"
  },
  {
    "name":"Brandon",
    "start":"left",
    "pre_moves":[
      {"count":112, "type":"delay"},
      {"count":8, "type":"delay"},
      {"count":8, "type":"right"},
      {"count":4, "type":"up"},
      {"count":12, "type":"left"},
      {"count":4, "type":"diag se pivot"},
      {"count":4, "type":"pose"},
      {"count":4, "dx":-3, "dy":-2, "type":"pivot"},
      {"count":4, "type":"pose"},
      {"count":4, "dx":3, "dy":-2, "type":"pivot"},
      {"count":4, "type":"pose"},
      {"count":8, "type":"up"},
      {"count":4, "type":"pose"},
      {"count":1, "dx":2, "dy":1, "type":""},
      {"count":11, "type":"down"}
    ],
    "color":"gray"
  },
  {
    "name":"Christina",
    "start":"left",
    "pre_moves":[
      {"count":112, "type":"delay"},
      {"count":12, "type":"delay"},
      {"count":8, "type":"right"},
      {"count":4, "type":"up"},
      {"count":8, "type":"left"},
      {"count":8, "type":"up"},
      {"count":4, "type":"pose"},
      {"count":1, "dx":2, "dy":1, "type":""},
      {"count":11, "type":"down"}
    ],
    "color":"gray"
  },
  {
    "name":"Jeremy G",
    "start":"left",
    "pre_moves":[
      {"count":112, "type":"delay"},
      {"count":16, "type":"delay"},
      {"count":8, "type":"right"},
      {"count":4, "type":"up"},
      {"count":4, "type":"left"},
      {"count":8, "type":"up"},
      {"count":4, "type":"pose"},
      {"count":1, "dx":-2, "dy":1, "type":""},
      {"count":11, "type":"down"}
    ],
    "color":"gray"
  },
  {
    "name":"Maggie",
    "start":"left",
    "pre_moves":[
      {"count":112, "type":"delay"},
      {"count":20, "type":"delay"},
      {"count":8, "type":"right"},
      {"count":4, "type":"up"},
      {"count":4, "type":"diag sw pivot"},
      {"count":4, "type":"pose"},
      {"count":4, "dx":3, "dy":-2, "type":"pivot"},
      {"count":4, "type":"pose"},
      {"count":4, "dx":-3, "dy":-2, "type":"pivot"},
      {"count":4, "type":"pose"},
      {"count":8, "type":"up"},
      {"count":4, "type":"pose"},
      {"count":1, "dx":-2, "dy":1, "type":""},
      {"count":11, "type":"down"}
    ],
    "color":"gray"
  },
  {
    "name":"Eric",
    "start":"left",
    "pre_moves":[
      {"count":112, "type":"delay"},
      {"count":24, "type":"delay"},
      {"count":8, "type":"right"},
      {"count":4, "type":"diag nw pivot"},
      {"count":4, "type":"pose"},
      {"count":8, "type":"up"},
      {"count":4, "type":"pose"},
      {"count":1, "dx":-2, "dy":1, "type":""},
      {"count":11, "type":"down"}
    ],
    "color":"gray"
  },
  {
    "name":"Julianne",
    "start":"left",
    "pre_moves":[
      {"count":112, "type":"delay"},
      {"count":28, "type":"delay"},
      {"count":4, "type":"right"},
      {"count":4, "dx":3, "dy":-2, "type":"pivot"},
      {"count":4, "type":"pose"},
      {"count":4, "dx":-3, "dy":-2, "type":"pivot"},
      {"count":4, "type":"pose"},
      {"count":8, "type":"up"},
      {"count":4, "type":"pose"},
      {"count":1, "dx":-2, "dy":1, "type":""},
      {"count":11, "type":"down"}
    ],
    "color":"gray"
  },
  {
    "name":"Iris",
    "start":"left",
    "pre_moves":[
      {"count":192, "type":"delay"},
      {"count":8, "type":"up"},
      {"count":4, "type":"diag ne"},
      {"count":4, "type":"pose"},
      {"count":1, "dx":-2, "dy":1, "type":""},
      {"count":7, "type":"down"},
      {"count":4, "dx":-6, "dy":0, "type":""},
      {"count":36, "type":"pose"},
      {"count":28, "type":"kneel"},
      {"count":4, "type":"pose"},
      {"count":4, "type":"right"},
      {"count":8, "type":"up"},
      {"count":1, "dx":1, "dy":1, "type":""},
      {"count":3, "type":"down"},
      {"count":16, "type":"pose"},
      {"count":8, "type":"down"},
      {"count":4, "dx":-5, "dy":0, "type":""},
      {"count":4, "type":"up"},
      {"count":16, "type":"pose"},
      {"count":4, "type":"right"},
      {"count":8, "type":"up"},
      {"count":1, "dx":1, "dy":1, "type":""},
      {"count":11, "type":"down"},
      {"count":4, "dx":-5, "dy":0, "type":""},
      {"count":4, "type":"up"},
      {"count":4, "type":"right"},
      {"count":8, "type":"up"},
      {"count":1, "dx":2, "dy":1, "type":""},
      {"count":11, "type":"down"}
    ],
    "color":"red"
  },
  {
    "name":"Jen",
    "start":"right",
    "pre_moves":[
      {"count":192, "type":"delay"},
      {"count":8, "type":"up"},
      {"count":4, "type":"diag nw"},
      {"count":4, "type":"pose"},
      {"count":1, "dx":2, "dy":1, "type":""},
      {"count":7, "type":"down"},
      {"count":4, "dx":6, "dy":0, "type":""},
      {"count":36, "type":"pose"},
      {"count":28, "type":"kneel"},
      {"count":4, "type":"pose"},
      {"count":16, "type":"pose"},
      {"count":4, "type":"left"},
      {"count":8, "type":"up"},
      {"count":1, "dx":-1, "dy":1, "type":""},
      {"count":3, "type":"down"},
      {"count":16, "type":"pose"},
      {"count":8, "type":"down"},
      {"count":4, "dx":5, "dy":0, "type":""},
      {"count":4, "type":"up"},
      {"count":4, "type":"left"},
      {"count":8, "type":"up"},
      {"count":1, "dx":-1, "dy":1, "type":""},
      {"count":11, "type":"down"},
      {"count":4, "dx":5, "dy":0, "type":""},
      {"count":4, "type":"up"},
      {"count":4, "type":"left"},
      {"count":8, "type":"up"},
      {"count":1, "dx":-2, "dy":1, "type":""},
      {"count":11, "type":"down"}
    ],
    "color":"blue"
  },
  {
    "name":"Peter",
    "start":"left",
    "pre_moves":[
      {"count":192, "type":"delay"},
      {"count":16, "type":"delay"},
      {"count":8, "type":"up"},
      {"count":4, "type":"diag ne"},
      {"count":4, "type":"pose"},
      {"count":1, "dx":-2, "dy":1, "type":""},
      {"count":7, "type":"down"},
      {"count":2, "type":"right"},
      {"count":22, "type":"pose"},
      {"count":28, "type":"kneel"},
      {"count":4, "type":"pose"},
      {"count":16, "type":"pose"},
      {"count":8, "type":"up"},
      {"count":1, "dx":-1, "dy":1, "type":""},
      {"count":7, "type":"down"},
      {"count":16, "type":"pose"},
      {"count":4, "type":"down"},
      {"count":4, "dx":5, "dy":0, "type":""},
      {"count":4, "type":"up"},
      {"count":4, "type":"left"},
      {"count":8, "type":"up"},
      {"count":1, "dx":-1, "dy":1, "type":""},
      {"count":11, "type":"down"},
      {"count":4, "dx":5, "dy":0, "type":""},
      {"count":4, "type":"up"},
      {"count":4, "type":"left"},
      {"count":8, "type":"up"},
      {"count":1, "dx":-2, "dy":1, "type":""},
      {"count":11, "type":"down"}
    ],
    "color":"blue"
  },
  {
    "name":"Shawn",
    "start":"right",
    "pre_moves":[
      {"count":192, "type":"delay"},
      {"count":16, "type":"delay"},
      {"count":8, "type":"up"},
      {"count":4, "type":"diag nw"},
      {"count":4, "type":"pose"},
      {"count":1, "dx":2, "dy":1, "type":""},
      {"count":7, "type":"down"},
      {"count":2, "type":"left"},
      {"count":22, "type":"pose"},
      {"count":28, "type":"kneel"},
      {"count":4, "type":"pose"},
      {"count":8, "type":"up"},
      {"count":1, "dx":1, "dy":1, "type":""},
      {"count":7, "type":"down"},
      {"count":16, "type":"pose"},
      {"count":4, "type":"down"},
      {"count":4, "dx":-5, "dy":0, "type":""},
      {"count":4, "type":"up"},
      {"count":4, "type":"right"},
      {"count":16, "type":"pose"},
      {"count":8, "type":"up"},
      {"count":1, "dx":1, "dy":1, "type":""},
      {"count":11, "type":"down"},
      {"count":4, "dx":-5, "dy":0, "type":""},
      {"count":4, "type":"up"},
      {"count":4, "type":"right"},
      {"count":8, "type":"up"},
      {"count":1, "dx":2, "dy":1, "type":""},
      {"count":11, "type":"down"}
    ],
    "color":"red"
  },
  {
    "name":"Allysa",
    "start":"left",
    "pre_moves":[
      {"count":192, "type":"delay"},
      {"count":32, "type":"delay"},
      {"count":8, "type":"up"},
      {"count":4, "type":"diag ne"},
      {"count":4, "type":"pose"},
      {"count":1, "dx":-2, "dy":1, "type":""},
      {"count":3, "type":"down"},
      {"count":2, "type":"left"},
      {"count":10, "type":"pose"},
      {"count":28, "type":"kneel"},
      {"count":4, "type":"pose"},
      {"count":4, "type":"up"},
      {"count":1, "dx":1, "dy":1, "type":""},
      {"count":11, "type":"down"},
      {"count":16, "type":"pose"},
      {"count":4, "dx":-5, "dy":0, "type":""},
      {"count":4, "type":"up"},
      {"count":4, "type":"right"},
      {"count":4, "type":"up"},
      {"count":16, "type":"pose"},
      {"count":4, "type":"up"},
      {"count":1, "dx":1, "dy":1, "type":""},
      {"count":11, "type":"down"},
      {"count":4, "dx":-5, "dy":0, "type":""},
      {"count":4, "type":"up"},
      {"count":4, "type":"right"},
      {"count":8, "type":"up"},
      {"count":1, "dx":2, "dy":1, "type":""},
      {"count":11, "type":"down"}
    ],
    "color":"red"
  },
  {
    "name":"Isabelle",
    "start":"right",
    "pre_moves":[
      {"count":192, "type":"delay"},
      {"count":32, "type":"delay"},
      {"count":8, "type":"up"},
      {"count":4, "type":"diag nw"},
      {"count":4, "type":"pose"},
      {"count":1, "dx":2, "dy":1, "type":""},
      {"count":3, "type":"down"},
      {"count":2, "type":"right"},
      {"count":10, "type":"pose"},
      {"count":28, "type":"kneel"},
      {"count":4, "type":"pose"},
      {"count":16, "type":"pose"},
      {"count":4, "type":"up"},
      {"count":1, "dx":-1, "dy":1, "type":""},
      {"count":11, "type":"down"},
      {"count":16, "type":"pose"},
      {"count":4, "dx":5, "dy":0, "type":""},
      {"count":4, "type":"up"},
      {"count":4, "type":"left"},
      {"count":4, "type":"up"},
      {"count":4, "type":"up"},
      {"count":1, "dx":-1, "dy":1, "type":""},
      {"count":11, "type":"down"},
      {"count":4, "dx":5, "dy":0, "type":""},
      {"count":4, "type":"up"},
      {"count":4, "type":"left"},
      {"count":8, "type":"up"},
      {"count":1, "dx":-2, "dy":1, "type":""},
      {"count":11, "type":"down"}
    ],
    "color":"blue"
  },
  {
    "name":"Nick L",
    "start":"middle left",
    "pre_moves":[
      {"count":192, "type":"delay"},
      {"count":48, "type":"delay"},
      {"count":8, "type":"up"},
      {"count":4, "dx":3, "dy":-4, "type":""},
      {"count":4, "type":"pose"},
      {"count":28, "type":"kneel"},
      {"count":4, "type":"pose"},
      {"count":16, "type":"pose"},
      {"count":1, "dx":-1, "dy":1, "type":""},
      {"count":11, "type":"down"},
      {"count":4, "dx":5, "dy":0, "type":""},
      {"count":16, "type":"pose"},
      {"count":4, "type":"up"},
      {"count":4, "type":"left"},
      {"count":8, "type":"up"},
      {"count":1, "dx":-1, "dy":1, "type":""},
      {"count":11, "type":"down"},
      {"count":4, "dx":5, "dy":0, "type":""},
      {"count":4, "type":"up"},
      {"count":4, "type":"left"},
      {"count":8, "type":"up"},
      {"count":1, "dx":-2, "dy":1, "type":""},
      {"count":11, "type":"down"}
    ],
    "color":"blue"
  },
  {
    "name":"John",
    "start":"middle right",
    "pre_moves":[
      {"count":192, "type":"delay"},
      {"count":48, "type":"delay"},
      {"count":8, "type":"up"},
      {"count":4, "dx":-3, "dy":-4, "type":""},
      {"count":4, "type":"pose"},
      {"count":28, "type":"kneel"},
      {"count":4, "type":"pose"},
      {"count":1, "dx":1, "dy":1, "type":""},
      {"count":11, "type":"down"},
      {"count":4, "dx":-5, "dy":0, "type":""},
      {"count":16, "type":"pose"},
      {"count":4, "type":"up"},
      {"count":4, "type":"right"},
      {"count":8, "type":"up"},
      {"count":16, "type":"pose"},
      {"count":1, "dx":1, "dy":1, "type":""},
      {"count":11, "type":"down"},
      {"count":4, "dx":-5, "dy":0, "type":""},
      {"count":4, "type":"up"},
      {"count":4, "type":"right"},
      {"count":8, "type":"up"},
      {"count":1, "dx":2, "dy":1, "type":""},
      {"count":11, "type":"down"}
    ],
    "color":"red"
  },
  {
    "name":"Sam",
    "start":"middle left",
    "pre_moves":[
      {"count":256, "type":"delay"},
      {"count":10, "type":"up"},
      {"count":2, "type":"pose"},
      {"count":20, "type":"pose"},
      {"count":10, "type":"down"},
      {"count":3, "dx":-5, "dy":0, "type":""},
      {"count":3, "dx":0, "dy":-4, "type":""},
      {"count":16, "type":"pose"},
      {"count":4, "type":"right"},
      {"count":8, "type":"up"},
      {"count":1, "dx":1, "dy":1, "type":""},
      {"count":3, "type":"down"},
      {"count":16, "type":"pose"},
      {"count":8, "type":"down"},
      {"count":4, "dx":-5, "dy":0, "type":""},
      {"count":4, "type":"up"},
      {"count":4, "type":"right"},
      {"count":8, "type":"up"},
      {"count":1, "dx":2, "dy":1, "type":""},
      {"count":11, "type":"down"}
    ],
    "color":"red"
  },
  {
    "name":"Kevin",
    "start":"middle right",
    "pre_moves":[
      {"count":256, "type":"delay"},
      {"count":10, "type":"up"},
      {"count":2, "type":"pose"},
      {"count":20, "type":"pose"},
      {"count":16, "type":"pose"},
      {"count":10, "type":"down"},
      {"count":3, "dx":5, "dy":0, "type":""},
      {"count":3, "dx":0, "dy":-4, "type":""},
      {"count":16, "type":"pose"},
      {"count":4, "type":"left"},
      {"count":8, "type":"up"},
      {"count":1, "dx":-1, "dy":1, "type":""},
      {"count":3, "type":"down"},
      {"count":8, "type":"down"},
      {"count":4, "dx":5, "dy":0, "type":""},
      {"count":4, "type":"up"},
      {"count":4, "type":"left"},
      {"count":8, "type":"up"},
      {"count":1, "dx":-2, "dy":1, "type":""},
      {"count":11, "type":"down"}
    ],
    "color":"blue"
  },
  {
    "name":"Sabrina",
    "start":"middle left",
    "pre_moves":[
      {"count":256, "type":"delay"},
      {"count":8, "type":"delay"},
      {"count":6, "type":"up"},
      {"count":2, "type":"pose"},
      {"count":16, "type":"pose"},
      {"count":6, "type":"down"},
      {"count":4, "dx":-5, "dy":0, "type":""},
      {"count":3, "dx":0, "dy":-4, "type":""},
      {"count":3, "dx":4, "dy":0, "type":""},
      {"count":16, "type":"pose"},
      {"count":8, "type":"up"},
      {"count":1, "dx":1, "dy":1, "type":""},
      {"count":7, "type":"down"},
      {"count":16, "type":"pose"},
      {"count":4, "type":"down"},
      {"count":4, "dx":-5, "dy":0, "type":""},
      {"count":4, "type":"up"},
      {"count":4, "type":"right"},
      {"count":8, "type":"up"},
      {"count":1, "dx":2, "dy":1, "type":""},
      {"count":11, "type":"down"}
    ],
    "color":"red"
  },
  {
    "name":"Eurie",
    "start":"middle right",
    "pre_moves":[
      {"count":256, "type":"delay"},
      {"count":8, "type":"delay"},
      {"count":6, "type":"up"},
      {"count":2, "type":"pose"},
      {"count":16, "type":"pose"},
      {"count":16, "type":"pose"},
      {"count":6, "type":"down"},
      {"count":4, "dx":5, "dy":0, "type":""},
      {"count":3, "dx":0, "dy":-4, "type":""},
      {"count":3, "dx":-4, "dy":0, "type":""},
      {"count":16, "type":"pose"},
      {"count":8, "type":"up"},
      {"count":1, "dx":-1, "dy":1, "type":""},
      {"count":7, "type":"down"},
      {"count":4, "type":"down"},
      {"count":4, "dx":5, "dy":0, "type":""},
      {"count":4, "type":"up"},
      {"count":4, "type":"left"},
      {"count":8, "type":"up"},
      {"count":1, "dx":-2, "dy":1, "type":""},
      {"count":11, "type":"down"}
    ],
    "color":"blue"
  },
  {
    "name":"Elaine",
    "start":"middle left",
    "pre_moves":[
      {"count":256, "type":"delay"},
      {"count":16, "type":"delay"},
      {"count":4, "dx":-5, "dy":0, "type":""},
      {"count":12, "type":"pose"},
      {"count":4, "type":"up"},
      {"count":4, "type":"right"},
      {"count":8, "type":"up"},
      {"count":16, "type":"pose"},
      {"count":1, "dx":1, "dy":1, "type":""},
      {"count":11, "type":"down"},
      {"count":4, "dx":-5, "dy":0, "type":""},
      {"count":16, "type":"pose"},
      {"count":4, "type":"up"},
      {"count":4, "type":"right"},
      {"count":8, "type":"up"},
      {"count":1, "dx":1, "dy":1, "type":""},
      {"count":11, "type":"down"},
      {"count":4, "dx":-5, "dy":0, "type":""},
      {"count":4, "type":"up"},
      {"count":4, "type":"right"},
      {"count":8, "type":"up"},
      {"count":1, "dx":2, "dy":1, "type":""},
      {"count":11, "type":"down"}
    ],
    "color":"red"
  },
  {
    "name":"Chris M",
    "start":"middle right",
    "pre_moves":[
      {"count":256, "type":"delay"},
      {"count":16, "type":"delay"},
      {"count":4, "dx":5, "dy":0, "type":""},
      {"count":12, "type":"pose"},
      {"count":16, "type":"pose"},
      {"count":4, "type":"up"},
      {"count":4, "type":"left"},
      {"count":8, "type":"up"},
      {"count":16, "type":"pose"},
      {"count":1, "dx":-1, "dy":1, "type":""},
      {"count":11, "type":"down"},
      {"count":4, "dx":5, "dy":0, "type":""},
      {"count":4, "type":"up"},
      {"count":4, "type":"left"},
      {"count":8, "type":"up"},
      {"count":1, "dx":-1, "dy":1, "type":""},
      {"count":11, "type":"down"},
      {"count":4, "dx":5, "dy":0, "type":""},
      {"count":4, "type":"up"},
      {"count":4, "type":"left"},
      {"count":8, "type":"up"},
      {"count":1, "dx":-2, "dy":1, "type":""},
      {"count":11, "type":"down"}
    ],
    "color":"blue"
  },
  {
    "name":"June (J)",
    "start":"middle left",
    "pre_moves":[
      {"count":256, "type":"delay"},
      {"count":24, "type":"delay"},
      {"count":8, "type":"pose"},
      {"count":4, "dx":-5, "dy":0, "type":""},
      {"count":4, "type":"up"},
      {"count":4, "type":"right"},
      {"count":4, "type":"up"},
      {"count":16, "type":"pose"},
      {"count":4, "type":"up"},
      {"count":1, "dx":1, "dy":1, "type":""},
      {"count":11, "type":"down"},
      {"count":16, "type":"pose"},
      {"count":4, "dx":-5, "dy":0, "type":""},
      {"count":4, "type":"up"},
      {"count":4, "type":"right"},
      {"count":8, "type":"up"},
      {"count":1, "dx":2, "dy":1, "type":""},
      {"count":11, "type":"down"}
    ],
    "color":"red"
  },
  {
    "name":"Michelle F",
    "start":"middle right",
    "pre_moves":[
      {"count":256, "type":"delay"},
      {"count":24, "type":"delay"},
      {"count":8, "type":"pose"},
      {"count":16, "type":"pose"},
      {"count":4, "dx":5, "dy":0, "type":""},
      {"count":4, "type":"up"},
      {"count":4, "type":"left"},
      {"count":4, "type":"up"},
      {"count":16, "type":"pose"},
      {"count":4, "type":"up"},
      {"count":1, "dx":-1, "dy":1, "type":""},
      {"count":11, "type":"down"},
      {"count":4, "dx":5, "dy":0, "type":""},
      {"count":4, "type":"up"},
      {"count":4, "type":"left"},
      {"count":8, "type":"up"},
      {"count":1, "dx":-2, "dy":1, "type":""},
      {"count":11, "type":"down"}
    ],
    "color":"blue"
  },
  {
    "name":"Derrick",
    "start":"right",
    "pre_moves":[
      {"count":384, "type":"delay"},
      {"count":4, "type":"right"},
      {"count":4, "type":"up"},
      {"count":4, "type":"left"},
      {"count":8, "type":"up"},
      {"count":48, "type":"pose"}
    ],
    "color":"green"
  },
  {
    "name":"Tim",
    "start":"left",
    "pre_moves":[
      {"count":384, "type":"delay"},
      {"count":4, "type":"left"},
      {"count":4, "type":"up"},
      {"count":4, "type":"right"},
      {"count":8, "type":"up"},
      {"count":48, "type":"pose"}
    ],
    "color":"red"
  }
]
