video_src="https://www.youtube.com/embed/n_zgqlUutvM";

pre_sections = [
  [4,8,"Intro"],
  [6,8,"Verse 1"],
  [6,8,"Chorus 1"],
  [6,8,"Verse 2"],
  [6,8,"Chorus 2"],
  [6,8,"Bridge"],
  [6,8,"Chorus 3"],
];

pre_comments = [
  [9,32,"Blue models interact! Positions don't matter"],
  [65,68,"Leave your luggage"],
  [75,78,"Pick up luggage"],
  [93,108,"Groups 1 and 2 sit down"],
  [117,120,"Groups 1 and 2 stand back up"],
  [137,168,"Blue models ignore each other"],
  [193,212,"Groups 1 and 2 face inwards, looking at the other model"],
  [241,256,"Make quarter circles"],
];

models = [
  {
    name:"Elizabeth",
    start: "left",
    pre_moves: [
      [8,"delay"],
      [4,-2,-2],
      [60,"pose"],
      [1,"up"],
      [3,"pose"],
      [4,3,0],
      [4,"up"],
      [2,"diag ne"],
      [2,"up"],
      [4,"pose"],
      [4,2,-1],
      [20,"pose"],
      [4,-1,1],
      [11,"down"],
    ],
    moves: [],
    color:"blue",
  },
  {
    name:"Christine",
    start: "left",
    pre_moves: [
      [16,"delay"],
      [4,-3,0],
      [52,"pose"],
      [1,"up"],
      [3,"pose"],
      [4,1,-2],
      [8,"pose"],
      [4,3,0],
      [4,"up"],
      [2,"diag ne"],
      [2,"up"],
      [4,"pose"],
      [4,2,1],
      [8,"pose"],
      [4,-1,0],
      [11,"down"],
    ],
    moves: [],
    color:"blue",
  },
  {
    name:"Sam",
    start: "left",
    pre_moves: [
      [24,"delay"],
      [4,-1,0],
      [44,"pose"],
      [1,"up"],
      [3,"pose"],
      [4,-2,0],
      [8,"pose"],
      [4,1,-2],
      [8,"pose"],
      [4,3,0],
      [4,"up"],
      [2,"diag ne"],
      [2,"up"],
      [4,"pose"],
      [11,"down"],
    ],
    moves: [],
    color:"blue",
  },

  {
    name:"Jeremy R",
    start: "right",
    pre_moves: [
      [8,"delay"],
      [4,2,-2],
      [60,"pose"],
      [1,"up"],
      [3,"pose"],
      [4,-3,0],
      [4,"up"],
      [2,"diag nw"],
      [2,"up"],
      [4,"pose"],
      [4,-2,-1],
      [20,"pose"],
      [4,1,1],
      [11,"down"],
    ],
    moves: [],
    color:"blue",
  },
  {
    name:"Nick P",
    start: "right",
    pre_moves: [
      [16,"delay"],
      [4,3,0],
      [52,"pose"],
      [1,"up"],
      [3,"pose"],
      [4,-1,-2],
      [8,"pose"],
      [4,-3,0],
      [4,"up"],
      [2,"diag nw"],
      [2,"up"],
      [4,"pose"],
      [4,-2,1],
      [8,"pose"],
      [4,1,0],
      [11,"down"],
    ],
    moves: [],
    color:"blue",
  },
  {
    name:"Michelle F",
    start: "right",
    pre_moves: [
      [24,"delay"],
      [4,1,0],
      [44,"pose"],
      [1,"up"],
      [3,"pose"],
      [4,2,0],
      [8,"pose"],
      [4,-1,-2],
      [8,"pose"],
      [4,-3,0],
      [4,"up"],
      [2,"diag nw"],
      [2,"up"],
      [4,"pose"],
      [11,"down"],
    ],
    moves: [],
    color:"blue",
  },

  {
    name:"John",
    start: "middle",
    pre_moves: [
      [76,"delay"],
      [12,"up"],
      [4,"pose"],
      [4,-1,-1],
      [20,"pose"],
      [4,-1,1],
      [11,"down"],
    ],
    moves: [],
    color:"purple",
  },
  {
    name:"Eurie",
    start: "middle",
    pre_moves: [
      [88,"delay"],
      [12,"up"],
      [4,"pose"],
      [4,1,-1],
      [8,"pose"],
      [4,1,1],
      [11,"down"],
    ],
    moves: [],
    color:"purple",
  },
  {
    name:"Alvin",
    start: "middle",
    pre_moves: [
      [100,"delay"],
      [12,"up"],
      [4,"pose"],
      [12,"down"],
    ],
    moves: [],
    color:"purple",
  },



  {
    name:"Cynthia",
    start: "left",
    pre_moves: [
      [32,"delay"],
      [8,8,-4],
      [4,"pose"],
      [4,"left"],
      [8,"up"],
      [4,"pose"],
      [4,"down"],
      [4,"pose"],
      [4,"down"],
      [4,"down pivot"],
    ],
    moves: [],
    color:"orange",
  },

  {
    name:"June (S)",
    start: "right",
    pre_moves: [
      [32,"delay"],
      [8,-7,-4],
      [4,"pose"],
      [4,"right"],
      [8,"up"],
      [4,"pose"],
      [4,"down"],
      [4,"pose"],
      [4,"down"],
      [4,"down pivot"],
    ],
    moves: [],
    color:"orange",
  },


  {
    name:"Kevin",
    start: "left",
    pre_moves: [
      [32,"delay"],
      [24,"delay"],
      [8,7,-4],
      [4,"pose"],
      [4,"left"],
      [8,"up"],
      [4,"pose"],
      [1,"diag se"],
      [7,"down"],
      [4,"down pivot"],
    ],
    moves: [],
    color:"green",
  },

  {
    name:"Dom",
    start: "right",
    pre_moves: [
      [32,"delay"],
      [24,"delay"],
      [8,-8,-4],
      [4,"pose"],
      [4,"right"],
      [1,"diag ne"],
      [7,"up"],
      [4,"pose"],
      [1,"diag sw"],
      [7,"down"],
      [4,"down pivot"],
    ],
    moves: [],
    color:"green",
  },



  {
    name:"Briana",
    start: "middle left",
    pre_moves: [
      [32,"delay"],
      [96,"delay"],
      [4,"up"],
      [4,"left"],
      [4,"pose"],
      [4,"right"],
      [8,"up"],
      [4,"pose"],
      [4,"down"],
      [4,"down pivot"],
      [4,"down"],
    ],
    moves: [],
    color:"orange",
  },
  {
    name:"Michael",
    start: "right",
    pre_moves: [
      [32,"delay"],
      [96,"delay"],
      [4,"up"],
      [4,"right"],
      [4,"pose"],
      [4,"left"],
      [8,"up"],
      [4,"pose"],
      [4,"down"],
      [4,"down pivot"],
      [4,"down"],
    ],
    moves: [],
    color:"orange",
  },


  {
    name:"Patrick",
    start: "middle right",
    pre_moves: [
      [32,"delay"],
      [96,"delay"],
      [24,"delay"],
      [4,"up"],
      [4,"right"],
      [4,"pose"],
      [4,"left"],
      [8,"up"],
      [4,"pose"],
      [1,"diag se"],
      [3,"down"],
      [4,"down pivot"],
      [4,"down"],
    ],
    moves: [],
    color:"green",
  },
  {
    name:"Jenett",
    start: "left",
    pre_moves: [
      [32,"delay"],
      [96,"delay"],
      [24,"delay"],
      [4,"up"],
      [4,"left"],
      [4,"pose"],
      [4,"right"],
      [1,"diag ne"],
      [7,"up"],
      [4,"pose"],
      [1,"diag sw"],
      [3,"down"],
      [4,"down pivot"],
      [4,"down"],
    ],
    moves: [],
    color:"green",
  },



  {
    name:"Eric",
    start: "left",
    pre_moves: [
      [136,"delay"],
      [4,-2,-2],
      [28,"pose"],
      [1,"up"],
      [3,"pose"],
      [4,3,0],
      [4,"up"],
      [2,"diag ne"],
      [2,"up"],
      [4,"pose"],
      [4,1,0],
      [20,"pose"],
      [11,"down"],
    ],
    moves: [],
    color:"blue",
  },
  {
    name:"Maggie",
    start: "left",
    pre_moves: [
      [144,"delay"],
      [4,-3,0],
      [20,"pose"],
      [1,"up"],
      [3,"pose"],
      [4,1,-2],
      [8,"pose"],
      [4,3,0],
      [4,"up"],
      [2,"diag ne"],
      [2,"up"],
      [4,"pose"],
      [4,1,1],
      [8,"pose"],
      [10,"down"],
    ],
    moves: [],
    color:"blue",
  },
  {
    name:"Julia",
    start: "left",
    pre_moves: [
      [152,"delay"],
      [4,-1,0],
      [12,"pose"],
      [1,"up"],
      [3,"pose"],
      [4,-2,0],
      [8,"pose"],
      [4,1,-2],
      [8,"pose"],
      [4,3,0],
      [4,"up"],
      [2,"diag ne"],
      [2,"up"],
      [4,"pose"],
      [1,-1,2],
      [10,"down"],
    ],
    moves: [],
    color:"blue",
  },

  {
    name:"Jeremy G",
    start: "right",
    pre_moves: [
      [136,"delay"],
      [4,2,-2],
      [28,"pose"],
      [1,"up"],
      [3,"pose"],
      [4,-3,0],
      [4,"up"],
      [2,"diag nw"],
      [2,"up"],
      [4,"pose"],
      [4,-1,0],
      [20,"pose"],
      [11,"down"],
    ],
    moves: [],
    color:"blue",
  },
  {
    name:"Brandon",
    start: "right",
    pre_moves: [
      [144,"delay"],
      [4,3,0],
      [20,"pose"],
      [1,"up"],
      [3,"pose"],
      [4,-1,-2],
      [8,"pose"],
      [4,-3,0],
      [4,"up"],
      [2,"diag nw"],
      [2,"up"],
      [4,"pose"],
      [4,-1,1],
      [8,"pose"],
      [10,"down"],
    ],
    moves: [],
    color:"blue",
  },
  {
    name:"Joe",
    start: "right",
    pre_moves: [
      [152,"delay"],
      [4,1,0],
      [12,"pose"],
      [1,"up"],
      [3,"pose"],
      [4,2,0],
      [8,"pose"],
      [4,-1,-2],
      [8,"pose"],
      [4,-3,0],
      [4,"up"],
      [2,"diag nw"],
      [2,"up"],
      [4,"pose"],
      [1,"diag se"],
      [10,"down"],
    ],
    moves: [],
    color:"blue",
  },

  {
    name:"Jeff",
    start: "middle",
    pre_moves: [
      [172,"delay"],
      [12,"up"],
      [4,"pose"],
      [4,2,0],
      [20,"pose"],
      [12,"down"],
    ],
    moves: [],
    color:"purple",
  },
  {
    name:"Rebecca",
    start: "middle",
    pre_moves: [
      [184,"delay"],
      [12,"up"],
      [4,"pose"],
      [4,-2,0],
      [8,"pose"],
      [12,"down"],
    ],
    moves: [],
    color:"purple",
  },
  {
    name:"Iris",
    start: "middle",
    pre_moves: [
      [196,"delay"],
      [12,"up"],
      [4,"pose"],
      [12,"down"],
    ],
    moves: [],
    color:"purple",
  },



  {
    name:"Derrick",
    start: "middle left",
    pre_moves: [
      [32,"delay"],
      [192,"delay"],
      [8,-4,-4],
      [4,"pose"],
      [4,"right"],
      [8,"up"],
      [16,"pose"],
      [4,"down"],
      [1,"diag se"],
      [7,"down"],
    ],
    moves: [],
    color:"green",
  },
  {
    name:"Tim",
    start: "middle right",
    pre_moves: [
      [32,"delay"],
      [192,"delay"],
      [8,4,-4],
      [4,"pose"],
      [4,"left"],
      [8,"up"],
      [24,"pose"],
      [2,"diag sw half speed"],
      [14,"down half speed"],
      [32,"pose"],
      [4,"down"],
    ],
    moves: [],
    color:"red",
  },




  {
    name:"Rebecca",
    start: "middle right",
    pre_moves: [
      [240,"delay"],
      [1,"right"],
      [1,1,-0.25],
      [1,1,-0.5],
      [1,0.85,-0.75],
      [1,0.65,-1],
      [1,0.5,-1.25],
      [2,"pose"],
      [40,"pose"],
      [1,-0.5,1.25],
      [1,"pose"],
      [1,-0.65,1],
      [1,"pose"],
      [1,-0.85,0.75],
      [1,"pose"],
      [1,-1,0.5],
      [1,"pose"],
      [1,-1,0.25],
      [1,"pose"],
      [1,"diag nw"],
      [3,"up"],
      [1,-1,-1],
      [7,"up"],
      [1,2,1],
      [11,"down"],
    ],
    moves: [],
    color:"orange",
  },
  {
    name:"Michael",
    start: "middle right",
    pre_moves: [
      [240,"delay"],
      [1,"delay"],
      [1,"right"],
      [1,1,-0.25],
      [1,1,-0.5],
      [1,0.85,-0.75],
      [1,0.65,-1],
      [2,"pose"],
      [40,"pose"],
      [1,-0.65,1],
      [1,"pose"],
      [1,-0.85,0.75],
      [1,"pose"],
      [1,-1,0.5],
      [1,"pose"],
      [1,-1,0.25],
      [1,"pose"],
      [1,"diag nw"],
      [3,"up"],
      [1,-1,-1],
      [7,"up"],
      [1,2,1],
      [11,"down"],
    ],
    moves: [],
    color:"orange",
  },
  {
    name:"Jenett",
    start: "middle right",
    pre_moves: [
      [240,"delay"],
      [2,"delay"],
      [1,"right"],
      [1,1,-0.25],
      [1,1,-0.5],
      [1,0.85,-0.75],
      [2,"pose"],
      [40,"pose"],
      [1,-0.85,0.75],
      [1,"pose"],
      [1,-1,0.5],
      [1,"pose"],
      [1,-1,0.25],
      [1,"pose"],
      [1,"diag nw"],
      [3,"up"],
      [1,-1,-1],
      [7,"up"],
      [1,2,1],
      [11,"down"],
    ],
    moves: [],
    color:"orange",
  },
  {
    name:"Patrick",
    start: "middle right",
    pre_moves: [
      [240,"delay"],
      [3,"delay"],
      [1,"right"],
      [1,1,-0.25],
      [1,1,-0.5],
      [2,"pose"],
      [40,"pose"],
      [1,-1,0.5],
      [1,"pose"],
      [1,-1,0.25],
      [1,"pose"],
      [1,"diag nw"],
      [3,"up"],
      [1,-1,-1],
      [7,"up"],
      [1,2,1],
      [11,"down"],
    ],
    moves: [],
    color:"orange",
  },
  {
    name:"Julia",
    start: "middle right",
    pre_moves: [
      [240,"delay"],
      [4,"delay"],
      [1,"right"],
      [1,1,-0.25],
      [2,"pose"],
      [40,"pose"],
      [1,-1,0.25],
      [1,"pose"],
      [1,"diag nw"],
      [3,"up"],
      [1,-1,-1],
      [7,"up"],
      [1,2,1],
      [11,"down"],
    ],
    moves: [],
    color:"orange",
  },
  {
    name:"Joe",
    start: "middle right",
    pre_moves: [
      [240,"delay"],
      [5,"delay"],
      [1,"right"],
      [2,"pose"],
      [40,"pose"],
      [1,"diag nw"],
      [3,"up"],
      [1,-1,-1],
      [7,"up"],
      [1,2,1],
      [11,"down"],
    ],
    moves: [],
    color:"orange",
  },



  {
    name:"June (S)",
    start: "middle left",
    pre_moves: [
      [240,"delay"],
      [1,"left"],
      [1,-1,-0.25],
      [1,-1,-0.5],
      [1,-0.85,-0.75],
      [1,-0.65,-1],
      [1,-0.5,-1.25],
      [2,"pose"],
      [40,"pose"],
      [1,"pose"],
      [1,0.5,1.25],
      [1,"pose"],
      [1,0.65,1],
      [1,"pose"],
      [1,0.85,0.75],
      [1,"pose"],
      [1,1,0.5],
      [1,"pose"],
      [1,1,0.25],
      [1,"pose"],
      [1,"diag ne"],
      [3,"up"],
      [1,1,-1],
      [7,"up"],
      [1,-2,1],
      [11,"down"],
    ],
    moves: [],
    color:"green",
  },
  {
    name:"Kevin",
    start: "middle left",
    pre_moves: [
      [240,"delay"],
      [1,"delay"],
      [1,"left"],
      [1,-1,-0.25],
      [1,-1,-0.5],
      [1,-0.85,-0.75],
      [1,-0.65,-1],
      [2,"pose"],
      [40,"pose"],
      [1,"pose"],
      [1,0.65,1],
      [1,"pose"],
      [1,0.85,0.75],
      [1,"pose"],
      [1,1,0.5],
      [1,"pose"],
      [1,1,0.25],
      [1,"pose"],
      [1,"diag ne"],
      [3,"up"],
      [1,1,-1],
      [7,"up"],
      [1,-2,1],
      [11,"down"],
    ],
    moves: [],
    color:"green",
  },
  {
    name:"Elizabeth",
    start: "middle left",
    pre_moves: [
      [240,"delay"],
      [2,"delay"],
      [1,"left"],
      [1,-1,-0.25],
      [1,-1,-0.5],
      [1,-0.85,-0.75],
      [2,"pose"],
      [40,"pose"],
      [1,"pose"],
      [1,0.85,0.75],
      [1,"pose"],
      [1,1,0.5],
      [1,"pose"],
      [1,1,0.25],
      [1,"pose"],
      [1,"diag ne"],
      [3,"up"],
      [1,1,-1],
      [7,"up"],
      [1,-2,1],
      [11,"down"],
    ],
    moves: [],
    color:"green",
  },
  {
    name:"Jeremy R",
    start: "middle left",
    pre_moves: [
      [240,"delay"],
      [3,"delay"],
      [1,"left"],
      [1,-1,-0.25],
      [1,-1,-0.5],
      [2,"pose"],
      [40,"pose"],
      [1,"pose"],
      [1,1,0.5],
      [1,"pose"],
      [1,1,0.25],
      [1,"pose"],
      [1,"diag ne"],
      [3,"up"],
      [1,1,-1],
      [7,"up"],
      [1,-2,1],
      [11,"down"],
    ],
    moves: [],
    color:"green",
  },
  {
    name:"Christine",
    start: "middle left",
    pre_moves: [
      [240,"delay"],
      [4,"delay"],
      [1,"left"],
      [1,-1,-0.25],
      [2,"pose"],
      [40,"pose"],
      [1,"pose"],
      [1,1,0.25],
      [1,"pose"],
      [1,"diag ne"],
      [3,"up"],
      [1,1,-1],
      [7,"up"],
      [1,-2,1],
      [11,"down"],
    ],
    moves: [],
    color:"green",
  },
  {
    name:"Nick P",
    start: "middle left",
    pre_moves: [
      [240,"delay"],
      [5,"delay"],
      [1,"left"],
      [2,"pose"],
      [40,"pose"],
      [1,"pose"],
      [1,"diag ne"],
      [3,"up"],
      [1,1,-1],
      [7,"up"],
      [1,-2,1],
      [11,"down"],
    ],
    moves: [],
    color:"green",
  },
]




lights = [
  {
    direction: "left",
    position: [0,0],
    length: 100,
    width: 20,
    pre_moves: [
      [4,"off"],
      [4,"on","fade in","color blue"],
      [4,"on","intensity 50%", "blue fade to red"],

    ],
    moves:[]
  }
]
