video_src="https://www.youtube.com/embed/UzXuQbcp8Yc";

pre_sections = [
  [4,6,"Duet Intro"],
  [4,8,"Intro"],
  [4,8,"Verse 1"],
  [4,8,"Pre Chorus 1"],
  [1,4,"Pause"],
  [8,8,"Chorus 1"],
  [4,8,"Verse 2"],
  [4,8,"Pre Chorus 2"],
  [1,4,"Pause"],
  [4,8,"Chorus 2"],
  [4,8,"Bridge 1"],
  [4,8,"Bridge 2"],
  [4,8,"Bridge 2 Repeat"],
  [4,8,"Chorus 3"],
  [4,8,"Chorus 3 Repeat"],
  [4,8,"Ending"],
];

pre_comments = [
  [1,24,"Beat can be hard to discern"],
  [25,188,"Dance; walk starts ~1:45"],
  [253,257,"Freeze 4cts"],
  [318,328,"Don't collide plz ty"],
  [329,336,"Make a semicircle"],
  [337,338,"Chris Y switch pose"],
  [339,340,"John switch pose"],
  [341,342,"June (J) switch pose"],
  [343,344,"Julia switch pose"],
  [345,346,"Jenett switch pose"],
  [347,348,"Jeremy G switch pose"],
  [349,350,"Allysa switch pose"],
  [351,352,"Michelle F switch pose"],
  [377,384,"Seizure warning"],
  [385,400,"Order doesn't matter, line up with your color"],
  [401,448,"Do a final group pose at the bottom of the T"],
];

models = [
  {
    name:"Derrick",
    start: [280,60],
    pre_moves: [
      [6,"pose"],
      [6,"pose"],
      [5,"down"],
      [1,"diag sw"],
      [6,"pose"],
    ],
    moves: [],
    color:"green",
  },
  {
    name:"Tim",
    start: "middle",
    pre_moves: [
      [6,"delay"],
      [6,"pose"],
      [5,"up"],
      [1,"diag ne"],
      [6,"pose"],
      [6,"down"],
    ],
    moves: [],
    color:"red",
  },


  {
    name:"Sam",
    start: "middle left",
    pre_moves: [
      [188,"delay"],
      [8,"up"],
      [4,"pose"],
      [1,"diag sw"],
      [3,"down"],
      [4,"left"],
      [20,"pose"],
      [6,4,4],
    ],
    moves: [],
    color:"green",
  },
  {
    name:"Eurie",
    start: "middle left",
    pre_moves: [
      [188,"delay"],
      [8,"delay"],
      [8,"up"],
      [4,"pose"],
      [1,"diag sw"],
      [3,"down"],
      [2,"left"],
      [14,"pose"],
      [5,2,4],
    ],
    moves: [],
    color:"green",
  },
  {
    name:"Brandon",
    start: "middle left",
    pre_moves: [
      [188,"delay"],
      [16,"delay"],
      [8,"up"],
      [4,"pose"],
      [1,"diag sw"],
      [3,"down"],
      [8,"pose"],
      [4,"down"],
    ],
    moves: [],
    color:"green",
  },
  {
    name:"Nick P",
    start: "middle left",
    pre_moves: [
      [188,"delay"],
      [24,"delay"],
      [8,"up"],
      [8,"pose"],
      [1,"diag sw"],
      [7,"down"],
    ],
    moves: [],
    color:"green",
  },

  {
    name:"Julianne",
    start: "middle right",
    pre_moves: [
      [188,"delay"],
      [8,"up"],
      [4,"pose"],
      [1,"diag se"],
      [3,"down"],
      [4,"right"],
      [20,"pose"],
      [6,-4,4],
    ],
    moves: [],
    color:"orange",
  },
  {
    name:"Briana",
    start: "middle right",
    pre_moves: [
      [188,"delay"],
      [8,"delay"],
      [8,"up"],
      [4,"pose"],
      [1,"diag se"],
      [3,"down"],
      [2,"right"],
      [14,"pose"],
      [5,-2,4],
    ],
    moves: [],
    color:"orange",
  },
  {
    name:"Michele T",
    start: "middle right",
    pre_moves: [
      [188,"delay"],
      [16,"delay"],
      [8,"up"],
      [4,"pose"],
      [1,"diag se"],
      [3,"down"],
      [8,"pose"],
      [4,"down"],
    ],
    moves: [],
    color:"orange",
  },
  {
    name:"Shyam",
    start: "middle right",
    pre_moves: [
      [188,"delay"],
      [24,"delay"],
      [8,"up"],
      [8,"pose"],
      [1,"diag se"],
      [7,"down"],
    ],
    moves: [],
    color:"orange",
  },



  {
    name:"Maggie",
    start: "middle",
    pre_moves: [
      [188,"delay"],
      [32,"delay"],
      [8,"up"],
      [4,1,-4],
      [4,"pose"],
      [1,"diag se"],
      [3,"down"],
      [4,"down pivot"],
      [4,"right"],
      [4,"pose"],
      [4,"pose"],
      [4,"diag sw"],
    ],
    moves: [],
    color:"orange",
  },
  {
    name:"ChaoLi",
    start: "middle",
    pre_moves: [
      [188,"delay"],
      [32,"delay"],
      [8,"delay"],
      [8,"up"],
      [4,1,-4],
      [4,"pose"],
      [1,"diag se"],
      [3,"down"],
      [4,"down pivot"],
      [4,"pose"],
      [4,"right"],
      [4,"pose"],
      [4,"diag sw"],
    ],
    moves: [],
    color:"orange",
  },
  {
    name:"Alvin",
    start: "middle",
    pre_moves: [
      [188,"delay"],
      [32,"delay"],
      [16,"delay"],
      [8,"up"],
      [4,1,-4],
      [4,"pose"],
      [4,"pose"],
      [1,"diag se"],
      [3,"down"],
      [4,"down pivot"],
      [4,"right"],
      [4,"pose"],
      [4,"diag sw"],
    ],
    moves: [],
    color:"orange",
  },
  {
    name:"Nick L",
    start: "middle",
    pre_moves: [
      [188,"delay"],
      [32,"delay"],
      [24,"delay"],
      [8,"up"],
      [4,"pose"],
      [4,1,-4],
      [4,"pose"],
      [1,"diag se"],
      [3,"down"],
      [4,"down pivot"],
      [4,"right"],
      [4,"pose"],
      [4,"diag sw"],
    ],
    moves: [],
    color:"orange",
  },

  {
    name:"Christine",
    start: "middle",
    pre_moves: [
      [188,"delay"],
      [32,"delay"],
      [4,"delay"],
      [8,"up"],
      [4,-1,-4],
      [4,"pose"],
      [1,"diag sw"],
      [3,"down"],
      [4,"down pivot"],
      [4,"left"],
      [4,"pose"],
      [4,"pose"],
      [4,"diag se"],
    ],
    moves: [],
    color:"green",
  },
  {
    name:"Joe",
    start: "middle",
    pre_moves: [
      [188,"delay"],
      [32,"delay"],
      [8,"delay"],
      [4,"delay"],
      [8,"up"],
      [4,-1,-4],
      [4,"pose"],
      [1,"diag sw"],
      [3,"down"],
      [4,"pose"],
      [4,"down pivot"],
      [4,"left"],
      [4,"pose"],
      [4,"diag se"],
    ],
    moves: [],
    color:"green",
  },
  {
    name:"Rebecca",
    start: "middle",
    pre_moves: [
      [188,"delay"],
      [32,"delay"],
      [16,"delay"],
      [4,"delay"],
      [8,"up"],
      [4,-1,-4],
      [4,"pose"],
      [4,"pose"],
      [1,"diag sw"],
      [3,"down"],
      [4,"down pivot"],
      [4,"left"],
      [4,"pose"],
      [4,"diag se"],
    ],
    moves: [],
    color:"green",
  },
  {
    name:"Shawn",
    start: "middle",
    pre_moves: [
      [188,"delay"],
      [32,"delay"],
      [24,"delay"],
      [4,"delay"],
      [4,"up"],
      [4,"pose"],
      [4,"up"],
      [4,-1,-4],
      [4,"pose"],
      [1,"diag sw"],
      [3,"down"],
      [4,"down pivot"],
      [4,"left"],
      [4,"pose"],
      [4,"diag se"],
    ],
    moves: [],
    color:"green",
  },










  {
    name:"Chris M",
    start: "middle",
    pre_moves: [
      [188,"delay"],
      [64,"delay"],
      [4,"delay"],
      [8,"up"],
      [4,1,-4],
      [4,"pose"],
      [1,"diag se"],
      [3,"down"],
      [4,"down pivot"],
      [4,"right"],
      [4,"pose"],
      [4,"diag sw"],
    ],
    moves: [],
    color:"orange",
  },
  {
    name:"Josh",
    start: "middle",
    pre_moves: [
      [188,"delay"],
      [64,"delay"],
      [4,"delay"],
      [8,"delay"],
      [8,"up"],
      [4,1,-4],
      [4,"pose"],
      [1,"diag se"],
      [3,"down"],
      [4,"down pivot"],
      [4,"right"],
      [4,"pose"],
      [4,"diag sw"],
    ],
    moves: [],
    color:"orange",
  },

  {
    name:"Jeff",
    start: "middle",
    pre_moves: [
      [188,"delay"],
      [64,"delay"],
      [4,"delay"],
      [4,"delay"],
      [8,"up"],
      [4,-1,-4],
      [4,"pose"],
      [1,"diag sw"],
      [3,"down"],
      [4,"down pivot"],
      [4,"left"],
      [4,"pose"],
      [4,"diag se"],
    ],
    moves: [],
    color:"green",
  },
  {
    name:"Patrick",
    start: "middle",
    pre_moves: [
      [188,"delay"],
      [64,"delay"],
      [4,"delay"],
      [8,"delay"],
      [4,"delay"],
      [8,"up"],
      [4,-1,-4],
      [4,"pose"],
      [1,"diag sw"],
      [3,"down"],
      [4,"down pivot"],
      [4,"left"],
      [4,"pose"],
      [4,"diag se"],
    ],
    moves: [],
    color:"green",
  },



  {
    name:"Elizabeth",
    start: "middle right",
    pre_moves: [
      [188,"delay"],
      [64,"delay"],
      [4,"delay"],
      [16,"delay"],
      [4,"delay"],
      [8,"up"],
      [4,-2,-4],
      [4,"pose"],
      [1,"diag sw"],
      [3,"down"],
      [4,"down pivot"],
      [4,"left"],
      [4,"pose"],
      [4,"diag se"],
    ],
    moves: [],
    color:"orange",
  },
  {
    name:"Christina",
    start: "middle right",
    pre_moves: [
      [188,"delay"],
      [64,"delay"],
      [4,"delay"],
      [16,"delay"],
      [4,"delay"],
      [8,"delay"],
      [8,"up"],
      [4,-2,-4],
      [4,"pose"],
      [1,"diag sw"],
      [3,"down"],
      [4,"down pivot"],
      [4,"left"],
      [4,"pose"],
      [4,"diag se"],
    ],
    moves: [],
    color:"orange",
  },
  {
    name:"Melody W",
    start: "middle right",
    pre_moves: [
      [188,"delay"],
      [64,"delay"],
      [4,"delay"],
      [16,"delay"],
      [4,"delay"],
      [16,"delay"],
      [8,"up"],
      [4,-2,-4],
      [4,"pose"],
      [1,"diag sw"],
      [3,"down"],
      [4,"down pivot"],
      [4,"down"],
    ],
    moves: [],
    color:"orange",
  },
  {
    name:"Kevin",
    start: "middle right",
    pre_moves: [
      [188,"delay"],
      [64,"delay"],
      [4,"delay"],
      [16,"delay"],
      [4,"delay"],
      [24,"delay"],
      [8,"up"],
      [4,-2,-4],
      [4,"pose"],
      [1,"diag sw"],
      [3,"down"],
      [4,"down pivot"],
      [4,"down"],
    ],
    moves: [],
    color:"orange",
  },

  {
    name:"Isabelle",
    start: "middle left",
    pre_moves: [
      [188,"delay"],
      [64,"delay"],
      [4,"delay"],
      [16,"delay"],
      [4,"delay"],
      [8,"up"],
      [4,2,-4],
      [4,"pose"],
      [1,"diag se"],
      [3,"down"],
      [4,"down pivot"],
      [4,"right"],
      [4,"pose"],
      [4,"diag sw"],
    ],
    moves: [],
    color:"green",
  },
  {
    name:"Michael",
    start: "middle left",
    pre_moves: [
      [188,"delay"],
      [64,"delay"],
      [4,"delay"],
      [16,"delay"],
      [4,"delay"],
      [8,"delay"],
      [8,"up"],
      [4,2,-4],
      [4,"pose"],
      [1,"diag se"],
      [3,"down"],
      [4,"down pivot"],
      [4,"right"],
      [4,"pose"],
      [4,"diag sw"],
    ],
    moves: [],
    color:"green",
  },
  {
    name:"Cynthia",
    start: "middle left",
    pre_moves: [
      [188,"delay"],
      [64,"delay"],
      [4,"delay"],
      [16,"delay"],
      [4,"delay"],
      [16,"delay"],
      [8,"up"],
      [4,2,-4],
      [4,"pose"],
      [1,"diag se"],
      [3,"down"],
      [4,"down pivot"],
      [4,"down"],
    ],
    moves: [],
    color:"green",
  },
  {
    name:"Elaine",
    start: "middle left",
    pre_moves: [
      [188,"delay"],
      [64,"delay"],
      [4,"delay"],
      [16,"delay"],
      [4,"delay"],
      [24,"delay"],
      [8,"up"],
      [4,2,-4],
      [4,"pose"],
      [1,"diag se"],
      [3,"down"],
      [4,"down pivot"],
      [4,"down"],
    ],
    moves: [],
    color:"green",
  },



  {
    name:"Julia",
    start: "middle right",
    pre_moves: [
      [188,"delay"],
      [128,"delay"],
      [4,"delay"],
      [6,"delay"],
      [8,0,-4,"half speed"],
      [18,"pose"],
      [2,1.75,0.75],
      [2,1.5,1.5],
      [2,0.75,1.75],
      [3,"left"],
    ],
    moves: [],
    color:"orange",
  },
  {
    name:"June (J)",
    start: "middle right",
    pre_moves: [
      [188,"delay"],
      [128,"delay"],
      [4,"delay"],
      [4,"delay"],
      [8,1.75,-3.25,"half speed"],
      [20,"pose"],
      [2,1.5,1.5],
      [2,0.75,1.75],
      [3,"left"],
    ],
    moves: [],
    color:"orange",
  },{
    name:"John",
    start: "middle right",
    pre_moves: [
      [188,"delay"],
      [128,"delay"],
      [4,"delay"],
      [2,"delay"],
      [8,3.25,-1.75,"half speed"],
      [22,"pose"],
      [2,0.75,1.75],
      [3,"left"],
    ],
    moves: [],
    color:"orange",
  },
  {
    name:"Chris Y",
    start: "middle right",
    pre_moves: [
      [188,"delay"],
      [128,"delay"],
      [4,"delay"],
      [8,4,0,"half speed"],
      [24,"pose"],
      [3,"left"],
    ],
    moves: [],
    color:"orange",
  },

  {
    name:"Jenett",
    start: "middle left",
    pre_moves: [
      [188,"delay"],
      [128,"delay"],
      [4,"delay"],
      [6,"delay"],
      [8,0,-4,"half speed"],
      [18,"pose"],
      [2,-1.75,0.75],
      [2,-1.5,1.5],
      [2,-0.75,1.75],
      [3,"right"],
    ],
    moves: [],
    color:"green",
  },
  {
    name:"Jereny G",
    start: "middle left",
    pre_moves: [
      [188,"delay"],
      [128,"delay"],
      [4,"delay"],
      [4,"delay"],
      [8,-1.75,-3.25,"half speed"],
      [20,"pose"],
      [2,-1.5,1.5],
      [2,-0.75,1.75],
      [3,"right"],
    ],
    moves: [],
    color:"green",
  },{
    name:"Allysa",
    start: "middle left",
    pre_moves: [
      [188,"delay"],
      [128,"delay"],
      [4,"delay"],
      [2,"delay"],
      [8,-3.25,-1.75,"half speed"],
      [22,"pose"],
      [2,-0.75,1.75],
      [3,"right"],
    ],
    moves: [],
    color:"green",
  },
  {
    name:"Michelle F",
    start: "middle left",
    pre_moves: [
      [188,"delay"],
      [128,"delay"],
      [4,"delay"],
      [8,-4,0,"half speed"],
      [24,"pose"],
      [3,"right"],
    ],
    moves: [],
    color:"green",
  },


  {
    name:"Sabrina",
    start: "middle right",
    pre_moves: [
      [188,"delay"],
      [160,"delay"],
      [4,"delay"],
      [24,"up half speed"],
      [8,"pose"],
      [10,"down"],
    ],
    moves: [],
    color:"orange",
  },
  {
    name:"Iris",
    start: "middle right",
    pre_moves: [
      [188,"delay"],
      [160,"delay"],
      [8,"delay"],
      [16,1,-8,"half speed"],
      [12,"pose"],
      [4,"up"],
      [1,"diag sw"],
      [9,"down"],
    ],
    moves: [],
    color:"orange",
  },
  {
    name:"Jen",
    start: "middle right",
    pre_moves: [
      [188,"delay"],
      [160,"delay"],
      [12,"delay"],
      [8,1,-4,"half speed"],
      [16,"pose"],
      [8,"up"],
      [1,"diag sw"],
      [9,"down"],
    ],
    moves: [],
    color:"orange",
  },
  {
    name:"Jeremy R",
    start: "middle right",
    pre_moves: [
      [188,"delay"],
      [160,"delay"],
      [16,"delay"],
      [12,5,-4,"half speed"],
      [8,"pose"],
      [4,"left"],
      [8,"up"],
      [1,"diag sw"],
      [9,"down"],
    ],
    moves: [],
    color:"orange",
  },
  {
    name:"Cynthia",
    start: "middle right",
    pre_moves: [
      [188,"delay"],
      [160,"delay"],
      [20,"delay"],
      [8,5,0,"half speed"],
      [8,"pose"],
      [4,"up"],
      [4,"left"],
      [8,"up"],
      [1,"diag sw"],
      [9,"down"],
    ],
    moves: [],
    color:"orange",
  },

  {
    name:"Eric",
    start: "middle left",
    pre_moves: [
      [188,"delay"],
      [160,"delay"],
      [4,"delay"],
      [24,"up half speed"],
      [8,"pose"],
      [10,"down"],
    ],
    moves: [],
    color:"green",
  },
  {
    name:"June (S)",
    start: "middle left",
    pre_moves: [
      [188,"delay"],
      [160,"delay"],
      [8,"delay"],
      [16,-1,-8,"half speed"],
      [12,"pose"],
      [4,"up"],
      [1,"diag se"],
      [9,"down"],
    ],
    moves: [],
    color:"green",
  },
  {
    name:"Peter",
    start: "middle left",
    pre_moves: [
      [188,"delay"],
      [160,"delay"],
      [12,"delay"],
      [8,-1,-4,"up half speed"],
      [16,"pose"],
      [8,"up"],
      [1,"diag se"],
      [9,"down"],
    ],
    moves: [],
    color:"green",
  },
  {
    name:"Dom",
    start: "middle left",
    pre_moves: [
      [188,"delay"],
      [160,"delay"],
      [16,"delay"],
      [12,-5,-4,"half speed"],
      [8,"pose"],
      [4,"right"],
      [8,"up"],
      [1,"diag se"],
      [9,"down"],
    ],
    moves: [],
    color:"green",
  },
  {
    name:"Michele T",
    start: "middle left",
    pre_moves: [
      [188,"delay"],
      [160,"delay"],
      [20,"delay"],
      [8,-5,0,"half speed"],
      [8,"pose"],
      [4,"up"],
      [4,"right"],
      [8,"up"],
      [1,"diag se"],
      [9,"down"],
    ],
    moves: [],
    color:"green",
  },



  {
    name:"C3O1",
    start: "right",
    pre_moves: [
      [188,"delay"],
      [192,"delay"],
      [4,"delay"],
      [4,"right"],
      [4,"up"],
      [4,"left"],
      [8,"up"],
      [1,"diag sw"],
      [9,"down"],
    ],
    moves: [],
    color:"orange",
  },
  {
    name:"C3O2",
    start: "right",
    pre_moves: [
      [188,"delay"],
      [192,"delay"],
      [6,"delay"],
      [4,"right"],
      [4,"up"],
      [4,"left"],
      [8,"up"],
      [1,"diag sw"],
      [9,"down"],
    ],
    moves: [],
    color:"orange",
  },
  {
    name:"C3O3",
    start: "right",
    pre_moves: [
      [188,"delay"],
      [192,"delay"],
      [8,"delay"],
      [4,"right"],
      [4,"up"],
      [4,"left"],
      [8,"up"],
      [1,"diag sw"],
      [9,"down"],
    ],
    moves: [],
    color:"orange",
  },
  {
    name:"C3O4",
    start: "right",
    pre_moves: [
      [188,"delay"],
      [192,"delay"],
      [10,"delay"],
      [4,"right"],
      [4,"up"],
      [4,"left"],
      [8,"up"],
      [1,"diag sw"],
      [9,"down"],
    ],
    moves: [],
    color:"orange",
  },
  {
    name:"C3O5",
    start: "right",
    pre_moves: [
      [188,"delay"],
      [192,"delay"],
      [12,"delay"],
      [4,"right"],
      [4,"up"],
      [4,"left"],
      [8,"up"],
      [1,"diag sw"],
      [9,"down"],
    ],
    moves: [],
    color:"orange",
  },
  {
    name:"C3O6",
    start: "right",
    pre_moves: [
      [188,"delay"],
      [192,"delay"],
      [14,"delay"],
      [4,"right"],
      [4,"up"],
      [4,"left"],
      [8,"up"],
      [1,"diag sw"],
      [9,"down"],
    ],
    moves: [],
    color:"orange",
  },
  {
    name:"C3O7",
    start: "right",
    pre_moves: [
      [188,"delay"],
      [192,"delay"],
      [16,"delay"],
      [4,"right"],
      [4,"up"],
      [4,"left"],
      [8,"up"],
      [1,"diag sw"],
      [9,"down"],
    ],
    moves: [],
    color:"orange",
  },
  {
    name:"C3O8",
    start: "right",
    pre_moves: [
      [188,"delay"],
      [192,"delay"],
      [18,"delay"],
      [4,"right"],
      [4,"up"],
      [4,"left"],
      [8,"up"],
      [1,"diag sw"],
      [9,"down"],
    ],
    moves: [],
    color:"orange",
  },
  {
    name:"C3O9",
    start: "right",
    pre_moves: [
      [188,"delay"],
      [192,"delay"],
      [20,"delay"],
      [4,"right"],
      [4,"up"],
      [4,"left"],
      [8,"up"],
      [1,"diag sw"],
      [9,"down"],
    ],
    moves: [],
    color:"orange",
  },
  {
    name:"C3O10",
    start: "right",
    pre_moves: [
      [188,"delay"],
      [192,"delay"],
      [22,"delay"],
      [4,"right"],
      [4,"up"],
      [4,"left"],
      [8,"up"],
      [1,"diag sw"],
      [9,"down"],
    ],
    moves: [],
    color:"orange",
  },
  {
    name:"C3O11",
    start: "right",
    pre_moves: [
      [188,"delay"],
      [192,"delay"],
      [24,"delay"],
      [4,"right"],
      [4,"up"],
      [4,"left"],
      [8,"up"],
      [1,"diag sw"],
      [9,"down"],
    ],
    moves: [],
    color:"orange",
  },
  {
    name:"C3O12",
    start: "right",
    pre_moves: [
      [188,"delay"],
      [192,"delay"],
      [26,"delay"],
      [4,"right"],
      [4,"up"],
      [4,"left"],
      [8,"up"],
      [1,"diag sw"],
      [9,"down"],
    ],
    moves: [],
    color:"orange",
  },
  {
    name:"C3O13",
    start: "right",
    pre_moves: [
      [188,"delay"],
      [192,"delay"],
      [28,"delay"],
      [4,"right"],
      [4,"up"],
      [4,"left"],
      [8,"up"],
      [1,"diag sw"],
      [9,"down"],
    ],
    moves: [],
    color:"orange",
  },
  {
    name:"C3O14",
    start: "right",
    pre_moves: [
      [188,"delay"],
      [192,"delay"],
      [30,"delay"],
      [4,"right"],
      [4,"up"],
      [4,"left"],
      [8,"up"],
      [1,"diag sw"],
      [9,"down"],
    ],
    moves: [],
    color:"orange",
  },
  {
    name:"C3O15",
    start: "right",
    pre_moves: [
      [188,"delay"],
      [192,"delay"],
      [32,"delay"],
      [4,"right"],
      [4,"up"],
      [4,"left"],
      [8,"up"],
      [1,"diag sw"],
      [9,"down"],
    ],
    moves: [],
    color:"orange",
  },
  {
    name:"C3O16",
    start: "right",
    pre_moves: [
      [188,"delay"],
      [192,"delay"],
      [34,"delay"],
      [4,"right"],
      [4,"up"],
      [4,"left"],
      [8,"up"],
      [1,"diag sw"],
      [9,"down"],
    ],
    moves: [],
    color:"orange",
  },
  {
    name:"C3O17",
    start: "right",
    pre_moves: [
      [188,"delay"],
      [192,"delay"],
      [36,"delay"],
      [4,"right"],
      [4,"up"],
      [4,"left"],
      [8,"up"],
      [1,"diag sw"],
      [9,"down"],
    ],
    moves: [],
    color:"orange",
  },
  {
    name:"C3O18",
    start: "right",
    pre_moves: [
      [188,"delay"],
      [192,"delay"],
      [38,"delay"],
      [4,"right"],
      [4,"up"],
      [4,"left"],
      [8,"up"],
      [1,"diag sw"],
      [9,"down"],
    ],
    moves: [],
    color:"orange",
  },
  {
    name:"C3O19",
    start: "right",
    pre_moves: [
      [188,"delay"],
      [192,"delay"],
      [40,"delay"],
      [4,"right"],
      [4,"up"],
      [4,"left"],
      [8,"up"],
      [1,"diag sw"],
      [9,"down"],
    ],
    moves: [],
    color:"orange",
  },
  {
    name:"Derrick",
    start: "right",
    pre_moves: [
      [188,"delay"],
      [192,"delay"],
      [42,"delay"],
      [4,"right"],
      [4,"up"],
      [4,"left"],
      [7,"up"],
      [1,"diag nw"],
      [32,"pose"],
    ],
    moves: [],
    color:"orange",
  },

  {
    name:"C3G1",
    start: "left",
    pre_moves: [
      [188,"delay"],
      [192,"delay"],
      [4,"delay"],
      [4,"left"],
      [4,"up"],
      [4,"right"],
      [8,"up"],
      [1,"diag se"],
      [9,"down"],
    ],
    moves: [],
    color:"green",
  },
  {
    name:"C3G2",
    start: "left",
    pre_moves: [
      [188,"delay"],
      [192,"delay"],
      [6,"delay"],
      [4,"left"],
      [4,"up"],
      [4,"right"],
      [8,"up"],
      [1,"diag se"],
      [9,"down"],
    ],
    moves: [],
    color:"green",
  },
  {
    name:"C3G3",
    start: "left",
    pre_moves: [
      [188,"delay"],
      [192,"delay"],
      [8,"delay"],
      [4,"left"],
      [4,"up"],
      [4,"right"],
      [8,"up"],
      [1,"diag se"],
      [9,"down"],
    ],
    moves: [],
    color:"green",
  },
  {
    name:"C3G4",
    start: "left",
    pre_moves: [
      [188,"delay"],
      [192,"delay"],
      [10,"delay"],
      [4,"left"],
      [4,"up"],
      [4,"right"],
      [8,"up"],
      [1,"diag se"],
      [9,"down"],
    ],
    moves: [],
    color:"green",
  },
  {
    name:"C3G5",
    start: "left",
    pre_moves: [
      [188,"delay"],
      [192,"delay"],
      [12,"delay"],
      [4,"left"],
      [4,"up"],
      [4,"right"],
      [8,"up"],
      [1,"diag se"],
      [9,"down"],
    ],
    moves: [],
    color:"green",
  },
  {
    name:"C3G6",
    start: "left",
    pre_moves: [
      [188,"delay"],
      [192,"delay"],
      [14,"delay"],
      [4,"left"],
      [4,"up"],
      [4,"right"],
      [8,"up"],
      [1,"diag se"],
      [9,"down"],
    ],
    moves: [],
    color:"green",
  },
  {
    name:"C3G7",
    start: "left",
    pre_moves: [
      [188,"delay"],
      [192,"delay"],
      [16,"delay"],
      [4,"left"],
      [4,"up"],
      [4,"right"],
      [8,"up"],
      [1,"diag se"],
      [9,"down"],
    ],
    moves: [],
    color:"green",
  },
  {
    name:"C3G8",
    start: "left",
    pre_moves: [
      [188,"delay"],
      [192,"delay"],
      [18,"delay"],
      [4,"left"],
      [4,"up"],
      [4,"right"],
      [8,"up"],
      [1,"diag se"],
      [9,"down"],
    ],
    moves: [],
    color:"green",
  },
  {
    name:"C3G9",
    start: "left",
    pre_moves: [
      [188,"delay"],
      [192,"delay"],
      [20,"delay"],
      [4,"left"],
      [4,"up"],
      [4,"right"],
      [8,"up"],
      [1,"diag se"],
      [9,"down"],
    ],
    moves: [],
    color:"green",
  },
  {
    name:"C3G10",
    start: "left",
    pre_moves: [
      [188,"delay"],
      [192,"delay"],
      [22,"delay"],
      [4,"left"],
      [4,"up"],
      [4,"right"],
      [8,"up"],
      [1,"diag se"],
      [9,"down"],
    ],
    moves: [],
    color:"green",
  },
  {
    name:"C3G11",
    start: "left",
    pre_moves: [
      [188,"delay"],
      [192,"delay"],
      [24,"delay"],
      [4,"left"],
      [4,"up"],
      [4,"right"],
      [8,"up"],
      [1,"diag se"],
      [9,"down"],
    ],
    moves: [],
    color:"green",
  },
  {
    name:"C3G12",
    start: "left",
    pre_moves: [
      [188,"delay"],
      [192,"delay"],
      [26,"delay"],
      [4,"left"],
      [4,"up"],
      [4,"right"],
      [8,"up"],
      [1,"diag se"],
      [9,"down"],
    ],
    moves: [],
    color:"green",
  },
  {
    name:"C3G13",
    start: "left",
    pre_moves: [
      [188,"delay"],
      [192,"delay"],
      [28,"delay"],
      [4,"left"],
      [4,"up"],
      [4,"right"],
      [8,"up"],
      [1,"diag se"],
      [9,"down"],
    ],
    moves: [],
    color:"green",
  },
  {
    name:"C3G14",
    start: "left",
    pre_moves: [
      [188,"delay"],
      [192,"delay"],
      [30,"delay"],
      [4,"left"],
      [4,"up"],
      [4,"right"],
      [8,"up"],
      [1,"diag se"],
      [9,"down"],
    ],
    moves: [],
    color:"green",
  },
  {
    name:"C3G15",
    start: "left",
    pre_moves: [
      [188,"delay"],
      [192,"delay"],
      [32,"delay"],
      [4,"left"],
      [4,"up"],
      [4,"right"],
      [8,"up"],
      [1,"diag se"],
      [9,"down"],
    ],
    moves: [],
    color:"green",
  },
  {
    name:"C3G16",
    start: "left",
    pre_moves: [
      [188,"delay"],
      [192,"delay"],
      [34,"delay"],
      [4,"left"],
      [4,"up"],
      [4,"right"],
      [8,"up"],
      [1,"diag se"],
      [9,"down"],
    ],
    moves: [],
    color:"green",
  },
  {
    name:"C3G17",
    start: "left",
    pre_moves: [
      [188,"delay"],
      [192,"delay"],
      [36,"delay"],
      [4,"left"],
      [4,"up"],
      [4,"right"],
      [8,"up"],
      [1,"diag se"],
      [9,"down"],
    ],
    moves: [],
    color:"green",
  },
  {
    name:"C3G18",
    start: "left",
    pre_moves: [
      [188,"delay"],
      [192,"delay"],
      [38,"delay"],
      [4,"left"],
      [4,"up"],
      [4,"right"],
      [8,"up"],
      [1,"diag se"],
      [9,"down"],
    ],
    moves: [],
    color:"green",
  },
  {
    name:"C3G19",
    start: "left",
    pre_moves: [
      [188,"delay"],
      [192,"delay"],
      [40,"delay"],
      [4,"left"],
      [4,"up"],
      [4,"right"],
      [8,"up"],
      [1,"diag se"],
      [9,"down"],
    ],
    moves: [],
    color:"green",
  },
  {
    name:"Melody T",
    start: "left",
    pre_moves: [
      [188,"delay"],
      [192,"delay"],
      [42,"delay"],
      [4,"left"],
      [4,"up"],
      [4,"right"],
      [7,"up"],
      [1,"diag ne"],
      [32,"pose"],
    ],
    moves: [],
    color:"green",
  },
];
